ocsigen/js_of_ocaml

lib/js.mli
Fix two typos on variable names in the comments.
=> fix two typos

compiler/js_parser.mly
Changes made:
* Factoring out operator definitions, instead of handling them inline:
* `comparison_or_logical_or_bit_operator`
* `comparison_or_logical_or_bit_operator_except_in`
* `arithmetic_or_shift_operator`
* `prefix_operator`
* `postfix_operator`
* Factoring out some productions like `parenthesised`
* Removal of redundant ocamlyacc-style `/* */` comments
* Using more conventional `*` and `?` operators instead of `list` and `option` productions
* Renaming many single-letter variables
* Using pattern-matching instead of `fst` and `snd` on tuples
=> Refactor JavaScript parser

runtime/stdlib.js
The problem occurs when you try to hash a block (like a record)
By keeping the two "break;" statements, the hash function will stop at the first string or float encountered.
See the following example:
```
type salted_pass = {
salt : string;
pass : string;
}
type user = {
login : string;
salt : string;
hash : int;
}
let create_user login salt pass =
{ login; salt; hash = Hashtbl.hash { salt; pass; }; }
let admin = create_user "login" "salt" "pass"
let auth { salt; hash; } pass =
Hashtbl.hash { salt; pass; } = hash
let () =
if auth admin "not pass"
then Format.printf "OK@."
else Format.printf "Error@."
```
In an OCaml toplevel, this example prints "Error" like we expect.
In the online Try Js_of_ocaml (and also in a real js_of_ocaml app), this will prints "Ok" because of the fact that the …
=> Stdlib.js: Fix bug in caml_hash

compiler/Makefile, lib/syntax/pa_js.ml
imported from https://github.com/astrada/pa_extjs cc @astrada
for the upcoming release or later
example 
```
let obj = {:
p1 = Js._true;
p2 = Js.string "string property";
:}
```
is infered to 
```
< p1 : < set : bool Js.t -> unit; .. > Js.gen_prop;
p2 : < set : Js.js_string Js.t -> unit; .. > Js.gen_prop;
.. >  Js.t
```
=> Syntax: object literal

runtime/stdlib.js
This adds the ability to parse infinities of various capitalisation
and sign. The following now works in the JS toplevel:
float_of_string (string_of_float infinity)
~~It's more permissive than standard ocaml, accepting, for example,
"infini" whereas that would be rejected by the normal toplevel.~~
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
=> Bring float_of_string more in line with the OCaml implementation.

lib/tyxml/tyxml_js.ml
This commit addresses #276. I refrained from modifying Dom_svg as we initially discussed, because the typing was not too obvious and would better be discussed in a separate issue.
=> Fixes the creation of SVG elements in Tyxml_js

lib/xmlHttpRequest.mli
As the HTTP methods are now in uppercase letters, update the doc accordingly. Thank to @rgrinberg for the catch.
=> Synchronize the doc with the actual type of override_method parameter.

compiler/inline.ml
This eliminates some simple calls to functions which immediately call another function or primitive.
It also adds some very naive logic to short-circuit calls to function which jump to another function.  This helps the inliner apply the elimination mentioned above.
=> Also inline simple functions which simply call another function or primitive

lib/xmlHttpRequest.ml, lib/xmlHttpRequest.mli
The method `send` accepts blob objects [1]
[1] https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest#send%28%29
=> XmlHttpRequest: send blob objects

lib/xmlHttpRequest.ml, lib/xmlHttpRequest.mli
I used a uselessly restrictive typing in my earlier commit, sorry!
=> XmlHttpRequest: fixed typing of send_blob

lib/.merlin
No such thing as menhir findlib package
@Drup follow up
=> menhir -> menhirLib in .merlin

runtime/bigarray.js
These are used by `ocplib-endian` which is used by `cstruct` which is used by most Mirage libraries. With these changes and a few others I could make an iocamljs notebook showing how to use the "vchan" shared-memory communication protocol:
http://djs55.github.io/ocaml-vchan/#
=> Implement caml_ba_uint8_{get,set}{16,32,64}

compiler/js_lexer.mll
float_of_string fails with hexa numbers on windows...
=> Fix for windows.

lib/tyxml/tyxml_js.ml, lib/tyxml/tyxml_js.mli
=> Lib: fix #333

compiler/flow.ml, lib/deriving_json/deriving_Json.mli, lib/ppx/ppx_js.cppo.ml, lib/syntax/pa_js.ml, tests/camlp4/meth.expected, tests/camlp4/prop.expected, tests/camlp4/write_prop.expected
the two syntax now generate the same OCaml code (modulo http://caml.inria.fr/mantis/view.php?id=6936)
=> Syntax: synchronize ppx and camlp4

lib/sys_js.ml, lib/sys_js.mli, runtime/io.js, toplevel/toplevel.cppo.ml
Trivial usage illustrated in the demo toplevel, where reads to stdin calls 'window.prompt'.
=> Allow to customize 'in_channel' with specific 'refiller'

opam
js_output.ml uses B64 which is not present in <= 1.1.0
=> Use base64 >= 2.0.0

.jenkins.sh, lib/tyxml/tyxml_js.ml, lib/tyxml/tyxml_js.mli, opam
This brings JSOO up-to-speed with the new-style wrapping available in current TyXML master. See ocsigen/tyxml#58 for the TyXML side of the story. This is an updated version of @drup's work in branch `less_wrap`.
=> New-Style TyXML Wrapping

lib/ppx/ppx_js.cppo.ml
This PR adjusts the code generated to help Merlin do its work, which suffered from the switch away from camlp4 (the-lambda-church/merlin#449).
The PPX generates multiple nodes at the same location in the Typedtree to improve the error messages.
But this confuses Merlin which is no longer able to map from cursor location to a node.
These patches add attributes and "ghostness" to help Melin navigates the tree.
Also, empty methods are ignored: these could be produced because of incomplete user input and caused an assertion to fail.
=> PPX: Add hints for Merlin

Makefile.conf, Makefile.filelist, lib/META, lib/Makefile, lib/deriving_json/deriving_Json.ml, lib/deriving_json/deriving_Json.mli, lib/ppx/ppx_deriving_json.ml, opam
This is a PPX version of our JSON deriving plug-in.
The generated code is somewhat different from the Camlp4 version. We follow the conventions of `ppx_deriving`, as opposed to the functorial style of (Camlp4) `deriving`.
The serialization format is the same, i.e., in principle you can dump `x` with Camlp4, parse the result with PPX, and get back `x`. Any divergence is a bug to be fixed.
I provide a few tests that demonstrate the syntax [as a Gist](https://gist.github.com/vasilisp/187ea176382511db3146).
=> Ppx deriving

lib/cSS.ml, lib/cSS.mli, lib/dom_html.ml, lib/dom_html.mli
common enough usage to be with `js_of_ocaml`
=> Add two helper functions

lib/Makefile
This is needed (at least on nixos) because with caml >= 4.02, camlp4 might not live
in the compiler's directory. See http://caml.inria.fr/mantis/view.php?id=6605
=> Use ocamlfind to find camlp4 everywhere

doc/api/index, lib/.depend, lib/Makefile, lib/jstable.ml, lib/jstable.mli
This module is backported from Eliom where it lived a very quiet life since its original commit 4 years ago.
For now, It's exactly the same as the one that was in eliom, but I think it would be interesting to see if there is a faster solution now.
@hhugo, I believe you did several such benchmark, any insights ?
I also wonder if we should change the API a little bit, so that to (partially) respect Hashtbl.S, but I'll wait for the above question to be answered first.
=> Add the Jstable module

doc/api/index, lib/.depend, lib/Makefile, lib/mutationObserver.ml, lib/mutationObserver.mli
A proposal for a binding to the mutation observers API. See also https://github.com/ocsigen/js_of_ocaml/issues/250
=> Mutation observers API: https://dom.spec.whatwg.org/#mutation-observers

lib/.depend, lib/Makefile, lib/worker.ml, lib/worker.mli
This code was developped for the OCaml MOOC. An embedding of the
toplevel into a WebWorker should follow in another PR.
=> Add bindings to WebWorker

doc/manual/src/bindings.wiki, doc/manual/src/camlp4.wiki, doc/manual/src/library.wiki, doc/manual/src/menu.wiki, lib/dom.mli, lib/dom_html.mli, lib/geolocation.mli, lib/js.mli, lib/lwt_js_events.mli, lib/mutationObserver.mli, lib/url.mli
I think I converted all of it.
The internals and the examples are still camlp4.
@hhugo @vouillon Should I convert the examples ? In this case, the ppx
should be loaded in the toplevel, instead of the camlp4 extension.
=> Convert documentation to ppx.

lib/dom_html.ml, lib/dom_html.mli
This where it belongs according to:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click
=> Dom: move `click` from `InputElement` to `HTMLElement`

lib/url.ml
This patch modifies the regexp used to parse URLs in function `Url.url_of_js_string`. It now matches URLs without a trailing slash.
=> Fix HTTP URL regexp to accept URLs without trailing slash

lib/url.ml
should return `[]` on `""`
`[""]` on `"/"`
`["";"a";""]` on `"/a/"`
etc (as everywhere else in Ocsigen and Ocamlnet).
=> Fix broken Url.path_of_path_string (was adding a slash at beginning)

README.md
Hi and thanks a lot for your compiler!
I'd like to offer a handful of small spelling corrections for the readme.
All the best,
Matthias Braun
=> Fix spelling of 'JavaScript'

compiler/inline.ml
E.g a block
```
=== 2 () ===
branch 2 ()
```
would cause the `follow_branch` function of `inline.ml` to loop.
Is this the correct way to fix #424 ?
=> Prevent inlining to loop on a block that immediately branches to itself

lib/dom_html.ml, lib/dom_html.mli
Readonly attribs for now. According to https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement there is also an setSelectionRange method to set these attributes, but unimplemented at the moment.
=> Dom_html: Add selection attributes to textarea.

jsoo_tools/jsoo_mktop.ml
The output with -verbose option was a little bit misleading in case of errors. (Error was displayed before appropriate command). We are flushing stdout now to prevent that.
=> jsoo_mktop: flushing stderr

lib/mutationObserver.ml, lib/mutationObserver.mli
The extra `Js.t` make you get a `Dom.node Js.t Js.t` when accessing to an element of the list.
=> Fixed MutationObserver.{added,removed}Nodes type.

compiler/.merlin, compiler/code.ml, compiler/code.mli, compiler/driver.ml, compiler/js_assign.ml, compiler/varPrinter.ml, compiler/varPrinter.mli
The invariant that a [Code.Var.t] is defined in a single scope does not hold.
We need to first fix
- closures compilation
- tailcall rewrite
Reverts ocsigen/js_of_ocaml#464
=> Revert "Compiler: Preserve ocaml names"

lib/tyxml/tyxml_js.ml, lib/tyxml/tyxml_js.mli
This is a request for comment on the interface.
I think this is the good set of functions we want :
- It allows to define everything in pure tyxml *and* to rely on a statically writen html
- It's rather safe
- It works well with reactive nodes (I think, cc @hhugo).
@talex5 See https://github.com/Drup/js-skeleton/blob/master/main.ml#L101 for a use-case.
Next remaining step to be able to define only-tyxml webpages is `Lwt_js_events`.
=> Add Tyxml_js.register

compiler/driver.ml, compiler/generate.ml, compiler/generate.mli, compiler/jsoo_compile.ml, compiler/linker.ml, compiler/linker.mli, compiler/parse_bytecode.ml, doc/Makefile, toplevel/Makefile, toplevel/toplevel.cppo.ml
Following https://github.com/ocsigen/js_of_ocaml/pull/313
Allow to dynlink precompiled ocaml units (aka javascript files).
In the toplevel, one can already do the following to compile bytecode to javascript and execute it. 
```
#load "/static/test_dynlink.cmo
```
One can now load precompiled javascript directly.
```
#load_js "test_dynlink.js"
```
https://github.com/ocsigen/js_of_ocaml/issues/369
https://github.com/ocsigen/js_of_ocaml/issues/450
=> Compiler: dynlink javascript files

lib/jsonp.ml, lib/jsonp.mli
This allows to avoid collisions, when integrating to other sites.
=> Add optional `prefix` arg to Jsonp.call

CHANGES, compiler/generate.ml, compiler/inline.ml, compiler/js_output.ml, compiler/js_parser.mly, compiler/parse_bytecode.ml, compiler/pretty_print.ml, doc/manual/src/debug.wiki, doc/manual/src/library.wiki, doc/manual/src/options.wiki, lib/OVERVIEW, lib/deriving_json/deriving_Json.ml, lib/dom.ml, lib/graphics/graphics_js.mli, lib/regexp.mli, ocamlbuild/ocamlbuild_js_of_ocaml.ml, runtime/nat.js
should just contain some trivial fixes in comments
=> spelling-fixes, as seen on lintian.debian.org

lib/dom_html.ml, lib/dom_html.mli
https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement
> Returns the currently focused element, that is, the element that will get keystroke events if the user types any. This attribute is read only.
> When there is no selection, the active element is the page's <body> or null.
=> Added document##.activeElement method.

lib/ppx/ppx_deriving_json.cppo.ml
Consider a type definition like
```ocaml
type a = b = A | ...
```
Our `ppx_deriving_json` plugin used to rely on the deriver for `b`, which does not necessarily exist (e.g., if `b` comes from a lower-level library that does not provide derivers). This patch produces a new deriver instead.
This came up while translating Eliom to PPX.
=> Fix ppx_deriving_json for types with both manifest and definition

Makefile.filelist, lib/META, lib/Makefile
Our runtime `deriving` components (`deriving_[Jj]son*` files, `js_of_ocaml.deriving` Findlib package) do not technically depend on the `deriving` package. They are used by both the `deriving` and `ppx_deriving` plugins. This PR updates the  build system to install the runtime components by default, so that they will be there for PPX.
We could make installation conditional on `deriving | ppx_deriving`, but it is not a lot of code, and theoretically somebody may want to use only the runtime part (say, for JSON-aware API but without directly using any deriver).
@Drup, would that fix #509 ?
=> Build deriving_[Jj]son.cm* even without deriving package

runtime/ieee_754.js
I was having a strange behavior when running a numeric program after converted to Js. I track down the problem and seems that the implementation of tanh is incorrect.
I used this mathematica code to check my implementation:
```
y = Exp[x];
z = Exp[-x];
FullSimplify[(y + z)/(y - z)] // This gives Coth[x]
FullSimplify[(y - z)/(y + z)] // This is Tanh[x]
```
=> Fixes the tanh implementation. The current implementation is coth

lib/deriving_json/deriving_Json.mli
The deriving_Json.mli file has "Convertion" written in it; the proper spelling is "Conversion".
=> deriving_Json.mli: fix spelling of "Conversion".

META.js_of_ocaml-camlp4
The `deriving` Camlp4 modules end up in the `deriving` subdirectory of `js_of_ocaml-camlp4`. We can use the `directory` directive in `META` to point to them.
=> Specify deriving dir in camlp4 META

lib/dom_html.ml, lib/dom_html.mli
When we use `aStorage##clear()`, the key value could be null.
=> Change type of Dom_html.storageEvent

META.js_of_ocaml-compiler.template, META.js_of_ocaml.template
fixes https://github.com/janestreet/jbuilder/issues/92
=> META: changes for weak

lib/lwt/lwt_xmlHttpRequest.ml
Instead we let the Browser figure out the header on its own. This relieves us of implementing the "boundary=..." argument which is missing in the current implementation.
=> Do not add "Content-Type: multipart/form-data" to HTTP POST requests

lib/sys_js.mli
Seems a previous name (`register_autoload`) was not corrected in the function's doc.
=> Updated doc of [mount]

lib/generate_stubs.sh, lib/jbuild
This change unbreaks the installation on FreeBSD.
=> Use jbuilder bash instead of /bin/bash

runtime/io.js
This PR fixes a runtime bug: the function `caml_ml_out_channels_list` should return a list of `chanid`'s (file descriptors), not a list of channel *objects*.  This function is only used in the implementation of `flush_all`, and the bug has been present for a long time, but it only became visible after the commit https://github.com/ocaml/ocaml/commit/1fc6ccb0877c282c93e78619882525fc4ab9209c#diff-9e690569dd7558fbf79622f41868ade5L335 which allowed the exception to escape.
Thanks to @Nevor for invaluable help finding the bug.
=> Fix caml_ml_out_channels_list

doc/manual/src/overview.wiki
Need this for ocsigen.org example
=> Add link to toplevel in introduction of js_of_ocaml

runtime/fs.js
I am using the js_of_ocaml library in a typescript project, generating CommonJS modules, and executed on a browser.
The problem is that js_of_ocaml assumes an environment supporting CommonJS is always a Node.js environment, so it uses MlNodeDevice, which requires 'fs' in its constructor.
This PR uses a detection method that is true in a Node.js environment, but not necessarily true in a CommonJS environment.
Discussion on Node.js environment detection: https://stackoverflow.com/questions/4224606/how-to-check-whether-a-script-is-running-under-node-js
The code of this PR is inspired from: https://stackoverflow.com/a/35813135
=> Improve node environment detection

CHANGES, lib/jbuild
One will have to explicitly open `Js_of_ocaml`.
@balat, @vouillon, any objection ?
=> Build: wrap js_of_ocaml lib

META.js_of_ocaml.template, doc/Makefile, doc/api/index, lib/lwt/log/jbuild, lib/lwt/log/lwt_log_js.ml, lib/lwt/log/lwt_log_js.mli
Reverts ocsigen/js_of_ocaml#670
=> Revert "Remove lwt-logger"

js_of_ocaml-lwt.opam, lib/lwt/log/jbuild
`lwt_log` depends on `lwt_unix` which we cannot compile to JavaScript...
=> Fix the dependencies of the Lwt logger

lib/dom_html.ml, lib/dom_html.mli
Fix DataTransfer class to match the interface: https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer
`DataTransfer.types` should be an array of strings
=> Lib: fix DataTransfer class interface

compiler/lib/driver.ml
Generate `Function("return this")()` instead of `function(){return this}()`. The former works in strict mode (for example under `node --use_strict` or when bundled using webpack), the latter doesn't.
Fixes #699.
=> Improved detection of global object

compiler/lib/driver.ml, compiler/lib/linker.ml, compiler/lib/linker.mli
This commit changes the linker to wrap each fragment in an immediately invoked function expression.  This prevents variables defined in one fragment from interfering with variable use defined in another, as well as preventing "use strict" from propagating across fragments.
=> Bundling external js files get more isolation.

.howdocgen
The `index.html` page (that Github Pages reads for url `ocsigen.org/js_of_ocaml/`) now redirects to the correct page.
=> Fix homepage's redirection target.

compiler/compileArg.ml
=> Fix: don't generate source if no-source-map passed

lib/js_of_ocaml/dom_svg.ml
Due to a typo ("foreignobject" instead of "foreignObject"),
Dom_svg.createForeignObject did not work. This PR fixes the
typo.
=> Fix Dom_svg.createForeignObject

compiler/tests/channel.ml, compiler/tests/stdio.ml, runtime/jslib.js
=> Runtime: fix encoding to standard outputs

compiler/lib/javascript.ml, compiler/tests/variable_declaration_output.ml
=> Compiler: fix compilation of floats

compiler/tests/std_marshal.ml, compiler/tests/test_marshal.ml, runtime/io.js, runtime/marshal.js, runtime/stdlib.js
Modified caml_output_val to correctly reflects sharing.
As a result, it avoids duplication and saves a lot of space.
This has been thoroughly tested by compiling Coq `.vo` files, where it can reduce the file size by an order of magnitude, and produces roughly the same size as the native `coqc`.
=> Runtime: more efficient (space-wise) marshalling.

CHANGES, lib/js_of_ocaml/dom.ml, lib/js_of_ocaml/dom.mli, lib/js_of_ocaml/dom_html.ml, lib/js_of_ocaml/dom_html.mli
The library seemed to be missing an accessible interface to give options to `addEventListener` as described in the specifications ( https://dom.spec.whatwg.org/#interface-eventtarget , https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Syntax , ... )
I added a function to do that.
Maybe the new class type will need to be moved, maybe some compatibility issues rise from the way I implemented this (some old browsers don't support the object variant. Maybe add a check for that ?)
Note: most times, users would need to pass only one option and keep the others at default. I don't know which is better between helper functions that take one argument and build the appropriate object, and additional class types with fewer methods.
=> Lib: Add support for 'addEventListener' with options object

runtime/fs_node.js
As discussed on ocamllabs slack, when a website includes Browserfs, it passes all the current `fs_node` detection logic but failed at runtime because `require` is undefined.
This PR handles this case by checking for `process.platform`
=> Handle browserfs in fs_node detection logic

lib/js_of_ocaml/xmlHttpRequest.ml, lib/js_of_ocaml/xmlHttpRequest.mli, lib/lwt/lwt_xmlHttpRequest.ml
From https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseText
> A DOMString which contains either the textual data received using the XMLHttpRequest or null if the request failed or "" if the request has not yet been sent by calling send().
=> Lib: change responseText signature

compiler/tests/obj.ml, compiler/tests/test_marshal.ml, runtime/marshal.js
This should allow one to add support for other custom blocks (e.g. bigarray, zarith Z.t)
cc @TyOverby
=> runtime: refactor marshal for custom blocks

lib/js_of_ocaml/dom.ml, lib/js_of_ocaml/dom.mli, lib/js_of_ocaml/dom_html.ml, lib/js_of_ocaml/dom_html.mli
* Added `customEvent` object type
* Added `Dom.createCustomEvent` and `Dom_html.createCustomEvent` helper functions to allow creation of custom events
* Added `eventTarget##dispatchEvent` method to allow dispatching of custom (and other) events
=> Added support for custom events

lib/js_of_ocaml/dom_html.ml, lib/js_of_ocaml/dom_html.mli
according to https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent, we have
[focusEvent] type which can be applied to [onblur] and [onfocus]. It
has one extra property than [Event] which is [relatedTarget]. This can
be useful in the case of focusable elements to trace down where the
focus has gone to or where the focus came from.
=> add focus event

CHANGES.md, lib/js_of_ocaml/dom_html.ml, lib/js_of_ocaml/dom_html.mli, lib/lwt/lwt_js_events.ml, lib/lwt/lwt_js_events.mli
Added bindings for pointer events to `Dom_html` and `Lwt_js_events` modules.
See [W3C](https://www.w3.org/TR/pointerevents/#pointerevent-interface) for pointer events API.
=> added bindings for pointer events

lib/tests/poly_compare.ml, runtime/stdlib.js
=> Fix polymorphic compare on JavaScript values

examples/README.md
Running the command as given in the readme resulted in
```
$ dune build @examples/DEFAULT
Error: Alias "DEFAULT" specified on the command line is empty.
It is not defined in examples or any of its descendants.
```
but the lower case alias worked as expected (as should be the case, given the dune files).
=> Correct build alias from DEFAULT to default in examples/README.md

compiler/lib/parse_bytecode.ml
That was the behavior of previous versions of Js_of_ocaml.
=> Dynlink/toplevel: export all units when no export file is specified

CHANGES.md, runtime/unix.js
Addresses https://github.com/ocsigen/js_of_ocaml/issues/913 and https://github.com/facebookexperimental/reason-native/issues/207
I tested this by running some JS tests compiled with Rely normally in a terminal and by piping the output to `cat` which should not be a tty. I also console logged the result of calling Unix.isatty on Unix.stdin to verify the function was returning the correct values. I thought I would need to provide values for Unix.stdin etc, but it was not necessary. I verified that the unix.isatty returns false and does not error in chrome as well.
I couldn't figure out the test structure of this repo and this change is fairly simple, so I did not add any automated tests, but could do so if desired with some help.
=> add stub for unix_isatty

lib/js_of_ocaml/dom_html.mli
When adding focusEvent to event type, I forgot to include the update for the event  type in dom_html. This pull request updates that.
=> Fix the type of blur and focus event to be focusEvent

compiler/tests/call_gen.ml, runtime/stdlib.js
A bug in the caml_callgen code was introduced in jane/js-of-ocaml/micro-optimze-runtime.                                                                                                                           
This bug manifests itself in this call-stack:                                                                                                                                                                      
> Uncaught TypeError: f.apply is not a function                                                                                                                                                                    
>    at caml_call_gen (stdlib.js:72) …
=> Hotfix runtime stdlib.js

lib/deriving_json/tests/json_convert.ml, lib/js_of_ocaml/js_of_ocaml_stubs.c, lib/js_of_ocaml/json.ml, runtime/ieee_754.js, runtime/int64.js, runtime/marshal.js, runtime/stdlib.js
Before we can merge this PR,
- we need to release 3.5.0 first
- update packages that depend on the current representation
=> Runtime: change representation of int64 

compiler/lib/config.ml, compiler/lib/javascript.ml, compiler/lib/js_traverse.ml, compiler/tests/util/util.ml, compiler/tests/util/util.mli, compiler/tests/variable_declaration_output.ml
Attempt to fix the `--enable vardecl` option.
partially fix #945
=> Compiler: fix vardecl optim

CHANGES.md, lib/js_of_ocaml/js_of_ocaml_stubs.c, lib/js_of_ocaml/typed_array.ml, lib/js_of_ocaml/typed_array.mli, lib/tests/typed_array.ml, runtime/bigarray.js
Follow-up on #969 
* Add `getInt16` do `dataView`
* Add `slice` to `typedArray ` and `arrayBuffer`
* Add `slice_toEnd` to `typedArray ` and `arrayBuffer`
* Add `*_fromGenarray` and `*_toGenarray` functions for each `typedArray` except `uint32` that is not supported by `Bigarray`
=> New methods and functions in Typed_array

compiler/lib/parse_js.ml
`fol` was not computed correctly in the presence of line directives
=> Fix parse js

lib/tests/test_fun_call.ml, runtime/jslib_js_of_ocaml.js, runtime/stdlib.js, runtime/stdlib_modern.js
Replacement for #993 and #994 
Commits should be read individually
The first commit revert the implement of caml_call_gen to the version before https://github.com/ocsigen/js_of_ocaml/commit/f8d2c7bf594271ede0066935d06f3865195f97e5
and adds many tests for functions wrapping callback and methods
Other commits fix or improve various stubs and update the newly added tests accordingly.
=> Fix caml_call_gen & co

lib/js_of_ocaml/js.mli
Since the rest of the manual mentions that ppx syntax is the recommended approach, we update it in the manual too.
=> replace camlp4 syntax with ppx syntax 

lib/js_of_ocaml/js_of_ocaml_stubs.c, lib/js_of_ocaml/xmlHttpRequest.ml, runtime/jslib_js_of_ocaml.js
fix #707 
One should be able to override the javascript function `caml_xmlhttprequest_create`
=> Runtime: fix #707

lib/tests/test_unsafe_set_get.ml, runtime/mlBytes.js
Until now, `MlBytes.toString()` would return a utf16 javascript string.
This is becoming problematic now that we want to change the representation of ocaml string to use JavaScript strings.
The reason is that JavaScript VMs will transparently rely on the toString method when converting a value to a primitive type. For example, the following snippet will behave differently depending on how we represent strings. 
```ocaml
let get o (name : string) = Js.Unsafe.get o name
```
```js
function get(o, name) { return o[name] }
```
- If implemented like ocaml bytes, a conversion from utf8 to utf16 will happen (the vm will call toString)
- If implemented like a javascript string, no conversion will happen
This PR propose to change the semantic of `MlBytes.toString()` to not apply the conversion to …
=> Change the semantic of MlBytes.toString

CHANGES.md, lib/js_of_ocaml/worker.ml, lib/js_of_ocaml/worker.mli
As it can be seen at https://developer.mozilla.org/en-US/docs/Web/API/ErrorEvent, the method of `ErrorMessage` to retrieve the message isn't called `msg` but `message`.
=> Rename `msg` method to `message` in `Worker` module

CHANGES.md, compiler/lib/js_output.ml, compiler/lib/js_simpl.ml, compiler/tests-compiler/cond.ml
- add a new regtest
- remove erroneous optimization when emitting JavaScript
- mitigate the previous code change by improving if-statement simplification.
=> Compiler: fix code generation for condition

CHANGES.md, compiler/lib/code.ml, compiler/lib/code.mli, compiler/lib/eval.ml, compiler/lib/flow.ml, compiler/lib/stdlib.ml, compiler/tests-jsoo/test_floats.ml
While randomly walking through the code, I noticed something similar
to an [old flambda bug](https://github.com/ocaml/ocaml/pull/1810). Indeed, with master, the following code (copied
from [this pull request](https://github.com/ocaml/ocaml/pull/1794#issuecomment-393820230)) prints `inf` instead of `-inf`:
```
let z =
let x = -0. and y = +0. in
if mod_float x 1. >= 0. then
x
else if false then x else y
let () =
Printf.printf "%g\n" (1. /. z)
```
The culprit is the use of the polymorphic equality on float values by a join
operation in the `Flow` module. This pull request ensure that the equality
function over `Code.constant` value does not use the polymorphic equality.
=> Avoid polymorphic comparison over float values

.ocamlformat, compiler/lib/specialize.ml, compiler/tests-compiler/recfun.ml, runtime/internalMod.js
The PR: 
- updates internalMod to not use the `.fun` property proxy for functions.
- adds an optimization to eliminate allocation of dummy function (`caml_alloc_dummy_function`). The dummy allocation is not necessary in JavaScript due to the weird non-lexical scoping.
Assuming the optimization properly eliminate all occurrences of `caml_alloc_dummy_function`,  we should be able to remove `.fun` property handling from the runtime.   
Note that `caml_alloc_dummy_function` was introduced in OCaml `4.02.3`, we would need to bump the lower bound from `4.02.0` to `4.02.3` which is fine.
=> Eliminate allocation of dummy function  

.ocamlformat, compiler/lib/parse_bytecode.ml
Hi, this is what the project would look like after being reformated with the current version (candidate) of ocamlformat 0.15.0.
**Please do not merge until ocamlformat.0.15.0 is available with opam.**
Please let me know if you see any regressions that I may have missed.
=> Upgrade to ocamlformat 0.15.0

lib/js_of_ocaml/resizeObserver.ml, lib/js_of_ocaml/resizeObserver.mli
borderBoxSize and contentBoxSize are actually arrays
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/borderBoxSize
=> Fix resize-observer

lib/js_of_ocaml/intersectionObserver.ml, lib/js_of_ocaml/intersectionObserver.mli
The Intersection Observer API provides a way to asynchronously observe
changes in the intersection of a target element with an ancestor element or
with a top-level document's viewport.
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
=> adds the intersection observer API

CHANGES.md, compiler/lib/parse_bytecode.ml
Fixes a segfault when `flat-float-array` mode is disabled.
=> Fix segfault when flat-float-array mode disabled

CHANGES.md, lib/js_of_ocaml/dom_html.ml, lib/js_of_ocaml/dom_html.mli
This seems to be supported in all common browsers now [1], and also seems part of the current html living spec [2].
[1] https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText
[2] https://html.spec.whatwg.org/multipage/dom.html#the-innertext-idl-attribute
=> add innerText to `Dom_html`

CHANGES.md, manual/rev-bindings.wiki
I got this error while looking for the "hello world" here: https://ocsigen.org/js_of_ocaml/latest/manual/rev-bindings
```
$ cat math.ml
let _ =
Js.export_all
(object%js
method add x y = x +. y
method abs x = abs_float x
val zero = 0.
end)
$ ocamlfind ocamlc -verbose \
-package js_of_ocaml -package js_of_ocaml-ppx \
-linkpkg math.ml -o math.byte
Effective set of compiler predicates: pkg_bytes,pkg_uchar,pkg_js_of_ocaml,pkg_js_of_ocaml-ppx,autolink,byte
+ ocamlc.opt -verbose -o math.byte -I /home/g/.opam/default/lib/bytes -I /home/g/.opam/default/lib/uchar -I /home/g/.opam/default/lib/js_of_ocaml -I /home/g/.opam/default/lib/js_of_ocaml-ppx -ppx "/home/g/.opam/default/lib/js_of_ocaml-ppx/./ppx.exe --as-ppx" /home/g/.opam/default/lib/js_of_ocaml/js_of_ocaml.cma math.ml
+ …
```
=> Fix `Error: Unbound module Js` when compiling math.ml

CHANGES.md, compiler/lib/parse_bytecode.ml, compiler/lib/stdlib.ml, toplevel/bin/jsoo_common.ml, toplevel/test/dune, toplevel/test/test_toplevel.ml, toplevel/test/test_toplevel.reference
extend #1130 
fix #1129 
- String.split_char had a surprising/wrong behavior of not round-tripping with String.concat. We can use the upstream one now that the minimal ocaml version is 4.04
- Add (minimal) testing for the toplevel
=> Fix toplevel generation

CHANGES.md, compiler/tests-io/cat.ml, compiler/tests-io/dune, runtime/io.js
Fix https://github.com/ocsigen/js_of_ocaml/issues/397
Makes https://github.com/grain-lang/grain/blob/main/compiler/grainc/jsoo_header.re obsolete (cc @phated)
=> Runtime: make stdin work on nodejs

CHANGES.md, compiler/tests-check-prim/output, compiler/tests-compiler/sys_fs.ml, compiler/tests-compiler/unix_fs.ml, runtime/fail.js, runtime/fs.js, runtime/fs_fake.js, runtime/fs_node.js, runtime/io.js, runtime/unix.js
This is just a draft right now because I need a lot of advice on TODOs and testing (sorry, first time contributing here).
@hhugo saw my work on these utilities in the Grain repository and said I should look into upstreaming them. So here is my first pass.
I tried changing some of our assumptions to allow for non-nodejs usage, but I don't know what the functions should do if not inside nodejs.
Please help guide me into taking this over the finish line! 🍻
=> Mapping ocaml unix APIs to nodejs calls

CHANGES.md, dune
Closes #1139 
I believe catching any exception that occurs while running `git log` will be more resilient than checking the `.git/` directory exists. I tested this with an esy resolution in Grain and it no longer crashes.
=> Always try to run git log but catch exception

CHANGES.md, compiler/bin-js_of_ocaml/compile.ml, compiler/lib/code.ml, compiler/lib/code.mli, compiler/lib/generate.ml, compiler/lib/parse_bytecode.ml, compiler/tests-compiler/empty_cma.ml
This PR removes the warning `Warning: '--source-map' is enabled but the bytecode program was compiled with` when compiling empty libraries. cc @abate
=> Compiler: better handling of empty libs

CHANGES.md, lib/js_of_ocaml/dom_html.ml, lib/js_of_ocaml/dom_html.mli, lib/js_of_ocaml/js_of_ocaml.ml, lib/js_of_ocaml/performanceObserver.ml, lib/js_of_ocaml/performanceObserver.mli
This is re-opened version of https://github.com/ocsigen/js_of_ocaml/pull/1123 to fix the bad state that I got the repo into. Sorry for the extra noise.
=> Lib: add message event types and PerformanceObserver

CHANGES.md, lib/js_of_ocaml/dom_html.ml, lib/js_of_ocaml/dom_html.mli
These APIs allow direct access to the declarations programatically.  They are especially useful for setting [css custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties).
- [CSSStyleDeclaration.setProperty](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty)
- [CSSStyleDeclaration.getPropertyValue](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/getPropertyValue)
- [CSSStyleDeclaration.getPropertyPriority](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/getPropertyPriority)
- [CSSStyleDeclaration.removeProperty](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/removeProperty)
=> Add Style Declaration Property Accessors

CHANGES.md, compiler/lib/js_output.ml
This reduces the time spent serializing of the js ast of `toplevel/examples/lwt_toplevel/toplevel.js` from 1.44 down to 0.62
=> Compiler: speedup emitting js files

CHANGES.md, ppx/ppx_deriving_json/lib/ppx_deriving_json.ml, ppx/ppx_deriving_json/tests/ppx.mlt
I discussed with @vouillon and he doesn't see why there should be this error. 
fix https://github.com/ocsigen/js_of_ocaml/issues/1184
=> PPX: removing the error concerning mutable fields

.ocamlformat, benchmarks/sources/ml/nucleic.ml, compiler/tests-jsoo/test_rec_mod.ml
This is a preview of the not-yet-released `ocamlformat.0.20.0`, please wait until the package is published in opam to merge this PR. The output is still likely to slightly change before the package is released.
The changes are due to:
- `module-item-spacing` is now set to `compact` for the default profile
- `module-item-spacing` is now correctly applied to mutually recursive type definitions
- formatting of list elements has been improved
=> [Preview] upgrade to ocamlformat.0.20.0

CHANGES.md, compiler/bin-js_of_ocaml/build_fs.ml, compiler/bin-js_of_ocaml/compile.ml, compiler/bin-jsoo_fs/jsoo_fs.ml, compiler/lib/code.ml, compiler/lib/code.mli, compiler/lib/eval.ml, compiler/lib/flow.ml, compiler/lib/flow.mli, compiler/lib/generate.ml, compiler/lib/inline.ml, compiler/lib/parse_bytecode.ml, compiler/lib/pseudo_fs.ml, compiler/lib/pseudo_fs.mli, compiler/lib/specialize.ml, compiler/lib/specialize_js.ml, compiler/tests-check-prim/output, lib/js_of_ocaml/js.ml, ppx/ppx_js/lib_internal/ppx_js_internal.ml, ppx/ppx_js/tests/ppx.mlt, runtime/fs.js
`IString` was introduced in #22 as a way to represent JavaScript strings and allow for more optimizations.
For example:
```ocaml
| Let(x, Prim (Extern "caml_js_from_string", Pc (String x))) when String.is_ascii s ->
Let(x, Constant (IString x))
```
Over time, this distinction got lost a bit and new code started to use `String` and `IString` inconsistently.
What this PR does:
- rename `IString` into `NativeString` to be more descriptive.
- go over the codebase and review all usage.
Note for reviewers:
- `NativeString` represent a js string (`Js.js_string Js.t`)
- `String` represent an ocaml string
=> Compiler: cleanup usage of IString (now NativeString) vs String

compiler/lib/eval.ml
This pull request tweaks the bounds checks for
switch indexes in `compiler/lib/eval.ml` in order
to handle negative indexes.
While the change seems sound and in line with
the comment about dead code, it is not entirely
clear to me whether this constitutes a proper fix
or is rather masking a deeper problem.
(I apologize for mistakenly pushing to `master`.)
=> Strengthen bound checks for switch indexes

CHANGES.md, compiler/bin-js_of_ocaml/build_fs.ml, compiler/bin-js_of_ocaml/compile.ml, compiler/bin-jsoo_fs/jsoo_fs.ml, compiler/lib/constant.ml, compiler/lib/driver.ml, compiler/lib/driver.mli, compiler/lib/linker.ml, compiler/lib/reserved.ml, compiler/tests-compiler/empty_cma.ml, compiler/tests-compiler/sourcemap.ml, lib/js_of_ocaml/js.ml, runtime/bigarray.js, runtime/bigstring.js, runtime/dynlink.js, runtime/fs.js, runtime/fs_node.js, runtime/graphics.js, runtime/ieee_754.js, runtime/jslib.js, runtime/jslib_js_of_ocaml.js, runtime/marshal.js, runtime/mlBytes.js, runtime/nat.js, runtime/stdlib.js, runtime/sys.js, runtime/toplevel.js, runtime/unix.js
fix https://github.com/ocsigen/js_of_ocaml/issues/699
=> Compiler: use globalThis, drop joo_global_object

compiler/lib/specialize_js.ml
I have an example in bap that ran into a stack overflow during dynamic linking. 
https://gist.github.com/philzook58/2bbec1b4cb58923b88325df37ccc3499
By finding what I think is an appropriate javascript stack trace as described in the gist, there were hundreds of `specialize_instrs` calls on top of the stack. Upon examining this function, it is indeed not tail recursive. Switching to accumulator passing style fixes the problem and now the example stack overflows at another point unrelated to dynamic linking, instead involving a CPS monad inside bap itself. This other problem can be fixed by reverting to bap 2.3.0, which did things differently, or perhaps by patching bap's monad to use a trampoline.
I also removed the `rem` term from the call to `specialize_instr` which perhaps was unwise …
=>  Accumulator Passing Style specialize_instrs

CHANGES.md, compiler/bin-js_of_ocaml/build_fs.ml, compiler/bin-js_of_ocaml/cmd_arg.ml, compiler/bin-js_of_ocaml/cmd_arg.mli, compiler/bin-js_of_ocaml/compile.ml, compiler/bin-jsoo_fs/jsoo_fs.ml, compiler/lib/constant.ml, compiler/lib/driver.ml, compiler/lib/driver.mli, compiler/lib/generate.ml, compiler/lib/generate.mli, compiler/tests-compiler/dune.inc, compiler/tests-compiler/error.ml, compiler/tests-compiler/exports.ml, compiler/tests-compiler/unix_fs.ml, compiler/tests-compiler/util/util.ml, compiler/tests-compiler/util/util.mli, examples/namespace/a.ml, examples/namespace/b.ml, examples/namespace/dune, examples/namespace/for-node.js, examples/namespace/index.html, lib/js_of_ocaml/js.ml, lib/js_of_ocaml/js_of_ocaml_stubs.c, runtime/jslib_js_of_ocaml.js
- properly export under node, fix #653
- allow to create multiple instances of the same program, fix #1171
=> Cleanup wrap-with-fun logic.

CHANGES.md, runtime/sys.js
=> Runtime: rely on crypto.getRandomValues when available

compiler/lib/eval.ml
It allows to remove the following deadcode from stdlib.ml
```
external major : unit -> unit = "caml_gc_major"
external naked_pointers_checked : unit -> bool
= "caml_sys_const_naked_pointers_checked"
let () = if naked_pointers_checked () then at_exit major
```
=> Compiler: static-eval caml_sys_const_naked_pointers_checked

CHANGES.md, compiler/bin-js_of_ocaml/js_of_ocaml.ml, compiler/lib-cmdline/arg.ml, compiler/lib-cmdline/arg.mli, compiler/lib/stdlib.ml, toplevel/examples/lwt_toplevel/dune
=> Compiler: new -Werror flag to turn wanrings into errors

CHANGES.md, compiler/lib/config.ml, compiler/lib/config.mli, compiler/lib/inline.ml
fix https://github.com/ocsigen/js_of_ocaml/issues/1185
=> Compiler: less agressive inlining

CHANGES.md, lib/js_of_ocaml/intl.ml, lib/js_of_ocaml/intl.mli
Fixes #1251
There may be (probably is) more missing options in the other `Intl` APIs. These two were the only one's I checked. If you want to be thorough I can go through the rest of them later though.
=> Lib: add missing Intl options

compiler/lib/reserved.ml
This adds a bunch of global values that are provided by the web platform. I annotated a couple with the platforms where they are available.
In the future, it'd be cool for these lists to be adjusted based on the `--target-env`
=> feat: Add more provided global values

CHANGES.md, README.md, manual/overview.wiki, runtime/weak.js
=> Runtime: proper semantic for weak

runtime/io.js
=> Runtime: flush output_channel if length over max length

CHANGES.md, runtime/jslib.js
We encountered a problem in the Grain LSP when compiled to JS. We were attempting to write a string that was >8096 bytes but  only 8096 bytes were being written. We dug into the nodejs source code and found that node only keeps a buffer with size 8096 around when you try to write on stdout or stderr.
The `process.stdout.write()` and `process.stderr.write()` functions that return a flag on whether the data was flushed, and any large content will result it in returning `false`. We dropped the chunk size down to 8 characters and it seems to flush instantly in a loop.
I left the `// TODO` comments in the code in case @hhugo thinks we should handle the `flushed` return value in some way.
=> fix: Only write small chunks to stdout/stderr in node

CHANGES.md, compiler/tests-check-prim/main.output, compiler/tests-check-prim/unix-unix.output, compiler/tests-check-prim/unix-win32.output, compiler/tests-compiler/unix_fs.ml, runtime/fs_fake.js, runtime/fs_node.js, runtime/unix.js
We needed these in Grain to provided externals needed by [reason-native `fs`](https://github.com/reasonml/reason-native/tree/master/src/fs) so I implemented in nodejs.
We're using these in our published binaries, but let me know if you'd like any changes.
=> feat: Implement unix_opendir and windows variants

compiler/lib/dune, lib/deriving_json/dune, lib/js_of_ocaml/dune, toplevel/bin/dune, toplevel/examples/server/dune, toplevel/lib/dune
Hello, I came across [this build](http://check.ocamllabs.io/log/1658671506-f1eef1a5b413443a841a24a1c7f655ef64772692/5.0+alpha-repo/bad/js_of_ocaml-compiler.4.0.0.1~alpha-repo) of your branch on `check.ocamllabs.io` and thought I would contribute what I hope to be a fix.
I'm quoting a colleague here at Tarides:
> 5.0.0~alpha1 corrects a mistake since the very beginning of jbuilder where packages insisted on adding the bytes package to libraries stanzas, even though there was no version of OCaml you could be using which didn't have the Bytes module
Thus my suggested fix is to remove `bytes` from any dune file that currently has it.
=> Removes bytes from dune files.

CHANGES.md, compiler/lib/generate.ml, compiler/lib/generate.mli, compiler/lib/linker.ml, compiler/lib/primitive.ml, compiler/lib/primitive.mli
and synchronize the information present in `generate.ml` and in the runtime.
The PR doesn't change the semantic. See #1311 for fixes.
=> Compiler: add a warning when we redefine the purity of a primitive

CHANGES.md, runtime/parsing.js
The parsing module runtime has a bug in `parsing.js`. 
In happened in the "ERROR_DETECTED" case. 
There's a break instruction that is breaking a for loop instead of breaking a switch. 
Which makes the "flow" fall through the "SHIFT" case instead of the "SHIFT_RECOVER" case. 
This PR adds a label to fix this. 
Here is a reproduction case, https://github.com/mlasson/js-yacc-bug
=> Bugfix in ocamlyacc runtime code 

CHANGES.md, compiler/lib/js_assign.ml, compiler/lib/js_traverse.ml, compiler/lib/js_traverse.mli
With nested functions, we are merging repeatedly the same set of variable usage information. It is more efficient to maintain a global table.
=> Js_traverse.freevar: performance improvement

CHANGES.md, compiler/lib/generate.ml
Cache computation of dominance frontier to avoid the quadratic behavior when dealing with long chains of simple branches.
- Add debug for dominance frontier timings.
- keeps the old implementation next to the new one, allowing to check that the two implementations give the same result.  
- the cache is invalidated every time we update the graph (when collapsing frontier / processing interm nodes).
Fixes #1300.
With the following exemple, dominance frontier timing goes from 14.43 s to 0.01 s.
```
ocaml <(echo "for i = 0 to 10000  do print_endline \"print_char '.';\"; done") > a.ml && ocamlc -g a.ml -o a.byte && _build/default/compiler/bin-js_of_ocaml/js_of_ocaml.exe --debuginfo --debug times  --pretty a.byte
```
=> Compiler: attempt to optimize computation of dominance frontier 

CHANGES.md, compiler/bin-jsoo_minify/jsoo_minify.ml, compiler/lib/driver.ml, compiler/lib/js_traverse.ml, compiler/lib/js_traverse.mli, compiler/tests-compiler/dune.inc, compiler/tests-compiler/minify.ml
It was inefficient for deeply nested functions since we were performing variable substitution repeatedly.
Also,
```javascript
var xx = 1;
function f () {
xx = 2; 
try {
throw 1
} catch (xx) { 
var xx = 3 
}; 
return xx;
}
function g () {
var xx = 2; 
return xx; 
}
```
was minified into
```javascript
var
xx=1;function
f(){xx=2;try{throw 1}catch(a){var
a=3}return xx}function
g(){var
xx=2;return xx}
```
which is wrong for `f` since `xx` is no longer declared locally.
And, we rename variables with the same name as a topelevel variable as in function `g`. I think the fix for #331 was overly conservative.
=> More efficient implementation of Js_traverse.rename_variable + fixes

CHANGES.md, compiler/tests-jsoo/gh_1307.ml, compiler/tests-jsoo/test_parsing.ml, runtime/parsing.js
While investigating #1307, I made this to try to understand what was going on. 
It implements the tracer of the `Parsing` module using `console.log` with minor differences with the native counterpart (`console.log` is adding spaces around values as well as some colors when executed with node). 
Feel free to close if not interested.
=> Implemement set_parser_trace

compiler/lib/code.ml, compiler/lib/code.mli, compiler/lib/deadcode.ml, compiler/lib/eval.ml, compiler/lib/flow.ml, compiler/lib/freevars.ml, compiler/lib/generate.ml, compiler/lib/generate_closure.ml, compiler/lib/inline.ml, compiler/lib/parse_bytecode.ml, compiler/lib/phisimpl.ml, compiler/lib/specialize.ml, compiler/lib/subst.ml, compiler/lib/tailcall.ml
The `handler` of a block doesn't seem to be useful. There was some renaming logic in `generate.ml` based on `handler` but I don't it ever triggers. Remove it allows to simplify the code a bit.
The PR also removes the second argument of the Poptrap constructor which was only used in parse_bytecode.
=> Compiler: get rid of block.handler

compiler/lib/generate.ml, compiler/lib/javascript.ml, compiler/lib/javascript.mli, compiler/lib/js_output.ml, compiler/lib/js_simpl.ml, compiler/tests-compiler/array_access.ml, compiler/tests-compiler/call_gen.ml, compiler/tests-compiler/cond.ml, compiler/tests-compiler/eliminate_exception_handler.ml, compiler/tests-compiler/exceptions.ml, compiler/tests-compiler/exports.ml, compiler/tests-compiler/gh1007.ml, compiler/tests-compiler/gh1051.ml, compiler/tests-compiler/gh1320.ml, compiler/tests-compiler/inlining.ml, compiler/tests-compiler/lazy.ml, compiler/tests-compiler/loops.ml, compiler/tests-compiler/match_with_exn.ml, compiler/tests-compiler/mutable_closure.ml, compiler/tests-compiler/obj.ml, compiler/tests-compiler/static_eval.ml, compiler/tests-compiler/tailcall.ml, compiler/tests-compiler/util/util.ml, compiler/tests-compiler/variable_declaration_output.ml
- rewrite `! (a > b)` into `(a<=b)` when applied to integers  (for other comparison ops)
- remove trailing `continue` statement in for-loops
- improve `Js_simpl.if_statement` to decrease nesting.
=> Compiler: some small size-optimisation 

CHANGES.md, compiler/lib/code.ml, compiler/lib/code.mli, compiler/lib/deadcode.ml, compiler/lib/eval.ml, compiler/lib/flow.ml, compiler/lib/freevars.ml, compiler/lib/generate.ml, compiler/lib/parse_bytecode.ml, compiler/lib/phisimpl.ml, compiler/lib/pure_fun.ml, compiler/lib/subst.ml, compiler/tests-compiler/dune.inc, compiler/tests-compiler/gh1354.ml, compiler/tests-compiler/util/util.ml, compiler/tests-compiler/util/util.mli
continues/replaces #1355 
fix #1354
=> Compiler: demonstrate and fix bug from 1354

CHANGES.md, lib/tyxml/tyxml_js.ml
#1268 has added support for proper weak semantic.
I forgot to update tyxml to take this into account.
=> Lib: fix 1352

CHANGES.md, compiler/lib/generate.ml, compiler/tests-compiler/call_gen.ml, compiler/tests-compiler/effects_toplevel.ml, compiler/tests-compiler/gh1051.ml, compiler/tests-compiler/gh1354.ml, lib/tests/dune.inc, lib/tests/gen-rules/gen.ml, lib/tests/test_fun_call.ml, runtime/jslib.js, runtime/stdlib.js, runtime/stdlib_modern.js
Getting the arity of a function is slow with `v8`. On Chrome, function `p` is about ten times slower than function `q`:
```javascript
function f (x) {}
f.l = 1;
var s = 0;
function p() {for (i = 0; i < 100000000; i++) { ((f.length)==1?s+=1:0)} }
function q(){for (i = 0; i < 100000000; i++) { ((f.l)==1?s+=1:0)}}
p(); q()
```
`node` takes 3.1s to execute this piece of code without this optimization and 1.3s with it (and 0,8s when manually removing the call to `caml_call1`).
```ocaml
let l = List.of_seq (Seq.init 10000 (fun i -> i))
let s = ref 0
let f x = s := !s + x
let iter f  = for i = 1 to 10000 do List.iter f l; s := 0; List.iter f l done
let () = iter f
```
I have known about this issue for a long time. I was considering wrapping functions inside an object: …
=> Apply functions: optimizations

compiler/tests-compiler/gh1051.ml, compiler/tests-compiler/unix_fs.ml, compiler/tests-compiler/util/util.ml, runtime/stdlib_modern.js
This fixes a bug in `stdlib_modern.js` that slipped in via https://github.com/ocsigen/js_of_ocaml/commit/23f4f71a9bdf77e4b2adac1ddee7d23471e7cbb4. Perhaps this repository should run the tests under both `stdlib.js` and `stdlib_modern.js`, so that bugs like this get caught earlier.
=> Cache function length correctly in stdlib_modern.js

CHANGES.md, compiler/lib/flow.ml, compiler/tests-compiler/dune.inc, compiler/tests-compiler/gh1390.ml, runtime/array.js, runtime/fail.js, runtime/jslib.js, runtime/obj.js, runtime/stdlib.js
We were not handling `Array.unsafe_get` correctly, and some annotations in the runtime were wrong.
=> Control flow analysis: fixes

runtime/stdlib.js, runtime/stdlib_modern.js
- We don't need to check for `f.fun` since, when it is set, function `f` is a wrapper that calls `f.fun`.
- We only need to check whether we still have a function in the over application case (`d < 0').
- We don't need a special case for `n === 0` since we now explictly set `f.l` for under-applied functions
=> Clean-up caml_call_gen

CHANGES.md, compiler/tests-check-prim/main.output, compiler/tests-check-prim/main.output5, compiler/tests-check-prim/unix-unix.output, compiler/tests-check-prim/unix-unix.output5, compiler/tests-check-prim/unix-win32.output, compiler/tests-check-prim/unix-win32.output5, compiler/tests-jsoo/test_rec_fun.ml, runtime/obj.js
Implement caml_alloc_dummy_infix
=> Fix compilation of some mutually recursive functions

CHANGES.md, compiler/bin-js_of_ocaml/cmd_arg.ml, compiler/bin-js_of_ocaml/compile.ml, compiler/lib-dynlink/js_of_ocaml_compiler_dynlink.ml, compiler/lib/link_js.ml, compiler/lib/ocaml_compiler.ml, compiler/lib/ocaml_compiler.mli, compiler/lib/parse_bytecode.ml, compiler/lib/parse_bytecode.mli, compiler/lib/stdlib.ml, compiler/lib/unit_info.ml, compiler/lib/unit_info.mli, compiler/tests-check-prim/main.output, compiler/tests-check-prim/main.output5, compiler/tests-check-prim/unix-unix.output, compiler/tests-check-prim/unix-unix.output5, compiler/tests-check-prim/unix-win32.output, compiler/tests-check-prim/unix-win32.output5, runtime/stdlib.js, runtime/toplevel.js, toplevel/examples/lwt_toplevel/dune, toplevel/examples/lwt_toplevel/effects_flags.ml, toplevel/examples/lwt_toplevel/index.html
Fix https://github.com/ocsigen/js_of_ocaml/issues/901
Rely on https://github.com/ocaml/dune/pull/6920
=> Separate compilation to generate toplevel

CHANGES.md, compiler/lib/config.ml, compiler/tests-check-prim/main.output, compiler/tests-check-prim/main.output5, compiler/tests-check-prim/unix-unix.output, compiler/tests-check-prim/unix-unix.output5, compiler/tests-check-prim/unix-win32.output
In that mode, an OCaml string will be represented as a JavaScript string containing a sequence of bytes. Converting the string to utf16 is still required for interaction with the DOM, or other javascript API.  
This current alternative representation of strings (implemented in #923) is not set in stone and could be changed based on benchmarks and usability.
Here are a bunch of things to consider:
- Wrap JavaScript string inside an object (`MlString`) to ease debugging.
- Update `string.ml` to make more optimization possible (`String.sub`, `(^)`, ..)
- Add more optimization in jsoo itself https://github.com/ocsigen/js_of_ocaml/pull/977  
**The PR is useful to check that existing program don't make any assumption about the internal representation of strings.**
=> Use javascript string by default

compiler/lib/global_flow.ml
Do not fail when accessing a constant string as if it were an array:
https://github.com/ocsigen/js_of_ocaml/blob/eae34864ebe70c3e93d373e87fcd7432f5a6d1d4/compiler/tests-jsoo/test_obj.ml#L49-L52
This fixes #1400.
=> Global flow analysis: fix assert failure

CHANGES.md, compiler/lib/effects.ml, compiler/lib/generate.ml, compiler/tests-check-prim/main.output, compiler/tests-check-prim/main.output5, compiler/tests-check-prim/unix-unix.output, compiler/tests-check-prim/unix-unix.output5, compiler/tests-check-prim/unix-win32.output, compiler/tests-check-prim/unix-win32.output5, compiler/tests-compiler/effects_continuations.ml, compiler/tests-compiler/effects_exceptions.ml, compiler/tests-compiler/eliminate_exception_handler.ml, compiler/tests-compiler/exceptions.ml, compiler/tests-compiler/exports.ml, compiler/tests-compiler/gh1354.ml, compiler/tests-compiler/loops.ml, compiler/tests-compiler/match_with_exn.ml, compiler/tests-compiler/mutable_closure.ml, compiler/tests-compiler/tailcall.ml, runtime/backtrace.js, runtime/fail.js, runtime/graphics.js, runtime/jslib.js, runtime/sys.js
Fix https://github.com/ocsigen/js_of_ocaml/issues/1347
Fix https://github.com/ocsigen/js_of_ocaml/issues/1045
One can control backtrace recording with OCAMLRUNPARAM env variable
```shell
$ OCAMLRUNPARAM=b=0 node ./q.js 12
Fatal error: exception Not_found
$ OCAMLRUNPARAM=b=1 node ./q.js 12
Fatal error: exception Not_found
/js_of_ocaml/q.js:1474
if(err.js_error) throw err.js_error;
^
Error: Js exception containing backtrace
at caml_exn_with_js_backtrace (/js_of_ocaml/q.js:31:21)
at caml_maybe_attach_backtrace (/js_of_ocaml/q.js:36:15)
at f (/js_of_ocaml/q.js:1560:25)
at f (/js_of_ocaml/q.js:1563:15)
at f (/js_of_ocaml/q.js:1563:15)
at /js_of_ocaml/q.js:1566:12
at Object.<anonymous> (/js_of_ocaml/q.js:1574:3)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at …
```
=> Fix js backtrace attached to ocaml exn 

manual/overview.wiki
I believe that the following disclaimer on the overview page of the manual would be helpful:
"Note: All code examples in this manual use Js_of_ocaml's ppx syntax.
It is, however, possible to use Js_of_ocaml purely as a compiler
while using a different package (e.g. gen_js_api, brr) to
provide bindings to the browser APIs."
This helps people understand that there are different ways to use js_of_ocaml (with ppx or with a different library that provides browser API bindings), and that they can only use the code examples from the manual if they are using the ppx. In particular, it is helpful to redirect people who are working on existing codebases that use jsoo without its ppx to their respective library docs.
If mentioning specific libraries that people use with jsoo is not reasonable, we …
=> Mention the use case as a compiler, without using the ppx syntax

CHANGES.md, compiler/lib-runtime-files/js_of_ocaml_compiler_runtime_files.ml, compiler/lib-runtime-files/tests/all.ml, compiler/tests-check-prim/main.output, compiler/tests-check-prim/main.output5, compiler/tests-check-prim/unix-unix.output, compiler/tests-check-prim/unix-unix.output5, compiler/tests-check-prim/unix-win32.output, compiler/tests-check-prim/unix-win32.output5, compiler/tests-runtime-events/dune, compiler/tests-runtime-events/test_runtime_events.ml, runtime/dune, runtime/runtime_events.js
https://github.com/ocaml/ocaml/pull/11474 introduces new primitives in the runtime that enables libraries to emit custom events in the runtime event tracing system. This feature will appear in the next release of OCaml.
For now the implementation is just a stub that does nothing with the event, so that linking with these libraries still works.
=> Support custom runtime events producer primitives

CHANGES.md, lib/js_of_ocaml/import.ml, lib/js_of_ocaml/js.ml, lib/tests/test_fun_call.ml
We discovered a bug caused by `caml_call_gen` removing logic for supporting the situation when it is called with a function whose length is 0. Arguably, this is not really a problem with `caml_call_gen` because it is only meant to be given _OCaml_ functions and not general Javascript functions; however, `Js.export` was implemented in such a way that this invariant is not always upheld, even if the `js_of_ocaml` library is used in a type-safe way.
This PR fixes the bug by changing `caml_call_gen`, rather than `Js.export`, since it seems possible for other code to be relying on this condition. I've looked for a while to see if I could find functions other than `Js.export`, but I couldn't find any, so I _think_ it's just that one function, but it's hard to be sure.
=> Runtime: restore support for zero-arity functions in caml_call_gen

compiler/lib/code.mli
The functions `Code.fold_closures` and `Code.fold_closures_innermost_first` are very useful but are not documented, and precise effect is not obvious. I propose to add the necessary documentation comments in the MLI.
=> Document two code folding functions

CHANGES.md, compiler/lib/js_parser.mly, compiler/tests-compiler/js_parser_printer.ml
Identifiers such as 'of' and 'async' are valid labels.
Fixes #1440.
=> JavaScript parser: fix parsing of labels

CHANGES.md, compiler/lib/js_parser.mly, compiler/lib/js_traverse.ml, compiler/lib/linker.ml, compiler/lib/parse_js.ml, compiler/lib/parse_js.mli, compiler/lib/source_map.ml, compiler/tests-compiler/js_parser_printer.ml, compiler/tests-sourcemap/dump.reference
Attempt to fix #1444.
Compared to master:
- max resident mem divided by 3 when parsing binaryen.es5.js
- time reduced by ~33% when parsing binaryen.es5.js
Time and memory are closer to what they were with jsoo 5.0 but are still a little higher
@phated, do you want to give this a try ?
=> Fix js parsing

benchmarks/Makefile, benchmarks/run.config
Fixes a deprecated option for Inkscape, and stop assuming that the JS engines are installed in /usr/bin.
Slightly unrelated: for me both inkscape and cairosvg crash when trying to convert the SVG graphs to PDF, am I the only one in this case?
(cairosvg command: `cairosvg <name>.svg -o <name>.pdf`)
=> Improve benchmarking scripts

benchmarks/Makefile
The `clean` Makefile target is not removed by `make clean`, resulting in errors if you run in sequence `make clean` and `make graphseff` (or `make clean` and just `make`).
=> Fix "clean" target for effect benchmarking

CHANGES.md, compiler/tests-jsoo/test_marshal.ml, runtime/marshal.js
Marshaling with jsoo when `use-js-string` is enabled could return incorrect result when sharing is involved.
This is because strrings were not considered for sharing, and would simply be ignored when computing offset of other shared object.
Fix #1456
=> Fix marshal sharing strings

benchmarks/run.config
0f2af26e771bdcdede6badf8fe1a411f604fc148 incorrectly commented out JS engines other than nodes. This commit reverts that.
=> Partly revert 0f2af26e771bdcdede6badf8fe1a411f604fc148

CHANGES.md, compiler/lib/js_output.ml, compiler/lib/js_parser.mly, compiler/lib/js_traverse.ml, compiler/lib/js_traverse.mli, compiler/lib/parse_js.ml, compiler/tests-compiler/js_parser_printer.ml, compiler/tests-compiler/minify.ml, dune-project, js_of_ocaml-compiler.opam
Fix the underlying issue in #1465
=> Bug fixes for 1465

CHANGES.md, compiler/lib/reserved.ml, runtime/bigarray.js
These arrays are used for example by [`ImageData`](https://developer.mozilla.org/en-US/docs/Web/API/ImageData) objects.
=> Support conversion of Uint8ClampedArray typed arrays to bigarrays.

CHANGES.md, runtime/jslib_js_of_ocaml.js
Recent versions of node define `navigator` but not `navigator.userAgent`.
=> Fix caml_js_on_ie

CHANGES.md, compiler/lib/global_flow.ml, compiler/tests-compiler/dune.inc, compiler/tests-compiler/gh1494.ml
In fast mode, we don't track function arguments, so we should consider them as escaping.
=> Fix global flow analysis

CHANGES.md, compiler/lib/generate.ml, compiler/lib/js_simpl.ml, compiler/lib/structure.ml, compiler/lib/structure.mli, compiler/tests-compiler/cond.ml, compiler/tests-compiler/exceptions.ml, compiler/tests-compiler/gh1007.ml, compiler/tests-compiler/gh747.ml, compiler/tests-compiler/lazy.ml, compiler/tests-compiler/loops.ml, compiler/tests-compiler/match_with_exn.ml, compiler/tests-compiler/mutable_closure.ml, compiler/tests-compiler/variable_declaration_output.ml, compiler/tests-full/stdlib.cma.expected.js
Instead of using additional variables, use labelled and break statements.
Fix #1336 
This PR includes a copy of wa_structture.ml from wasm_of_ocaml.
~~This PR just a proof of concept for now.~~
cc @vouillon
=> Compiler: refactor control flow compilation

compiler/lib/generate.ml, compiler/lib/javascript.ml, compiler/lib/javascript.mli, compiler/lib/js_assign.ml, compiler/lib/js_output.ml, compiler/lib/js_traverse.ml, compiler/tests-full/stdlib.cma.expected.js
Labels are named based on theirs nesting level and have consecutive names 
Fix #1502
=> Compiler: dense label names

CHANGES.md, lib/js_of_ocaml/dom_html.ml, lib/js_of_ocaml/dom_html.mli
Hi,
Tiny patch to add `download` attribute in `<a>`:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download
https://caniuse.com/download
=> Download attribute

compiler/tests-compiler/error.ml, compiler/tests-jsoo/bin/error1-unregister.expected, compiler/tests-jsoo/bin/error2-unregister.expected, compiler/tests-ocaml/lib-effects/unhandled_unlinked.reference, runtime/sys.js
A newline is already added by `console.error`.
=> Remove spurious newline when outputing uncaught exception

CHANGES.md, compiler/lib/deadcode.ml, compiler/tests-compiler/effects_continuations.ml
If we have some code like the following where `f` and `g` are not used otherwise,  neither `f` nor `g` have to be considered live.
```ocaml
let f = ref None
....
let () = f := Some g
```
More generally, an assignment `Set_field (x, _, y)` will not mark `x` as live and will mark `y` as live only if `x` is live.
=> Dead code elimination of some unused references

CHANGES.md, compiler/lib/js_output.ml, compiler/lib/js_parser.mly, compiler/lib/parse_js.ml, compiler/tests-compiler/js_parser_printer.ml
=> The async keyword should not be followed by a newline

CHANGES.md, runtime/unix.js
This PR fixes the JS implementation of the `caml_unix_lstat_64`and `caml_unix_stat_64` calls.
Per the OCaml documentation (https://github.com/ocaml/ocaml/blob/f9371a2ea294f75da793451ef7be5dc69aad6b53/otherlibs/unix/unix_unix.ml#L388), the `caml_unix_lstat_64` external function has type signature `string -> stats`. In particular, it is meant to return a value of type `stats`.
In the Js_of_ocaml implementation of that external function, however, it returns nothing at all. This results in an `undefined`, which will then proceed to wreak havoc.
`caml_unix_stat_64` is similar.
Added back the `return` for the `r` object.
=> fix: add missing return for `stat` Unix functions

CHANGES.md, compiler/lib/js_traverse.ml, compiler/tests-compiler/minify.ml
=> Compiler: fix free variable wrt parameter's default value

CHANGES.md, compiler/lib/js_traverse.ml, compiler/tests-compiler/minify.ml
=> Compiler: fix free variable for classes

CHANGES.md, lib/js_of_ocaml/url.ml
Dear js_of_ocaml maintainers,
This patch comes from an issue spotted in learn-ocaml (which heavily relies on js_of_ocaml), namely:
* https://github.com/ocaml-sf/learn-ocaml/issues/539
Note: I didn't recompile js_of_ocaml itself yet to test it, but I'm confident of the fix; to summarize what I understood:
1. learn-ocaml handles local urls of the form `http://localhost:8080/exercises/tp1/#tab=report`;
2. it contains some (js_of_)ocaml code such as **`Url.Current.set_fragment "tab=report"`** to this aim;
3. unfortunately the browser URL was always `http://localhost:8080/exercises/tp1/#tab%3Dreport`, which is not that legible!;
4. replacing the line of point 2. above with `Dom_html.window##.location##.hash := Js.bytestring "tab=report"` solves the issue.
* FTR, the `document.location.hash` is …
=> fix(url.ml): set_fragment need not any urlencode

CHANGES.md, compiler/bin-jsoo_minify/jsoo_minify.ml, compiler/lib/js_assign.ml, compiler/lib/js_traverse.ml, compiler/lib/js_traverse.mli, compiler/lib/stdlib.ml, compiler/tests-compiler/dune.inc, compiler/tests-compiler/minify.ml, compiler/tests-compiler/scopes.ml, compiler/tests-full/stdlib.cma.expected.js
=> Compiler: fix variable renaming for let, const and classes

CHANGES.md, compiler/bin-jsoo_minify/jsoo_minify.ml, compiler/lib/driver.ml, compiler/lib/javascript.ml, compiler/lib/javascript.mli, compiler/lib/js_output.ml, compiler/lib/js_parser.mly, compiler/lib/js_simpl.ml, compiler/lib/js_token.ml, compiler/lib/js_token.mli, compiler/lib/js_traverse.ml, compiler/lib/js_traverse.mli, compiler/lib/parse_js.ml, compiler/lib/stdlib.ml, compiler/tests-compiler/scopes.ml
=> Compiler: support for es6 import/export

CHANGES.md, compiler/lib/generate.ml, compiler/lib/structure.ml, compiler/tests-compiler/gh1007.ml, compiler/tests-compiler/loops.ml, compiler/tests-full/stdlib.cma.expected.js
initially based on #1333 and #1334, then rebased on #1496.
The current implementation exits a loop as soon as possible. The generated code would be better if we allowed part of the continuations to remains inside the for-loop.
=> Compiler: exit loop early

compiler/lib/global_deadcode.ml, compiler/tests-compiler/direct_calls.ml, compiler/tests-compiler/effects_toplevel.ml, compiler/tests-full/stdlib.cma.expected.js
@vouillon. @micahcantor https://github.com/ocsigen/js_of_ocaml/pull/1503 breaks tail call as mentioned by @vouillon
>  The global DCE does not preserve tail calls. We don't care normally since JavaScript does not support tail calls, but this makes a difference for the CPS transformation.
Except the `Generate_closure` pass does care about tail calls as it rewrite mutually recursive functions using a trampoline.
Do you see any issue with the change proposed here ?
=> Compiler: restore TCO of mutually recursive functions

CHANGES.md, compiler/lib/flow_lexer.ml, compiler/lib/javascript.ml, compiler/lib/javascript.mli, compiler/lib/js_output.ml, compiler/lib/js_parser.mly, compiler/lib/js_traverse.ml, compiler/tests-compiler/js_parser_printer.ml, compiler/tests-compiler/scopes.ml, runtime/zstd.js
Using tests available in https://github.com/tc39/test262-parser-tests
We now check that we can parse as much as `node` in strict mode.
- Accept more line separator as it affect automatic semi-colon insertion
- Fix assignment target on the LHS
- Fix default export of function and class declaration  
```
$ dune runtest compiler/tests-js-parser/
Summary:                                 
skip : 90
fail : 0
pass : 1893
```
=> Some more fix to the js parser.

.github/workflows/build.yml, CHANGES.md, compiler/lib/driver.ml, compiler/lib/generate.ml, compiler/lib/generate_closure.ml, compiler/lib/javascript.ml, compiler/lib/javascript.mli, compiler/lib/js_assign.ml, compiler/lib/subst.mli, compiler/tests-compiler/direct_calls.ml, compiler/tests-compiler/gh1007.ml, compiler/tests-compiler/gh1320.ml, compiler/tests-compiler/mutable_closure.ml, compiler/tests-compiler/tailcall.ml, compiler/tests-full/stdlib.cma.expected.js
=> No longer rely on iife for scoping inside loops

CHANGES.md, compiler/lib/global_deadcode.ml, compiler/tests-toplevel/test_toplevel.ml, compiler/tests-toplevel/test_toplevel.reference
Bug introduced in https://github.com/ocsigen/js_of_ocaml/pull/1503
When using the toplevel and evaluating an expression. The corresponding bytecode received by jsoo look like a function body. In particular, it contains `Return` instructions returning the evaluated expression. The global DCE think that these returned values are unused and removes them. The PR marks all values returned at "toplevel" as escaping.
cc @micahcantor @OlivierNicole
=> Compiler: fix toplevel with globaldeacode

compiler/tests-jsoo/flush_stubs.c
When importing jsoo into a project where the c compiler errors on warnings, this becomes problematic. Since void is a noop, this seems like a reasonable addition to upstream and make this file more portable.
=> Explicitly void unused c variable

CHANGES.md, compiler/lib/generate.ml, compiler/tests-compiler/compact.ml, compiler/tests-compiler/dune.inc, compiler/tests-compiler/gh1354.ml, compiler/tests-compiler/gh1559.ml, compiler/tests-compiler/mutable_closure.ml, compiler/tests-compiler/static_eval.ml, compiler/tests-compiler/util/util.ml, compiler/tests-compiler/util/util.mli, compiler/tests-full/stdlib.cma.expected.js
- partial revert of #1565
- fix #1531 (https://github.com/ocsigen/js_of_ocaml/issues/1530)
=> Compiler: Bug fix and cleanup

CHANGES.md, compiler/lib/generate.ml, compiler/lib/structure.ml, compiler/lib/structure.mli, compiler/tests-compiler/direct_calls.ml, compiler/tests-compiler/effects.ml, compiler/tests-compiler/effects_continuations.ml, compiler/tests-compiler/effects_exceptions.ml, compiler/tests-compiler/effects_toplevel.ml, compiler/tests-compiler/gh1007.ml, compiler/tests-compiler/gh1320.ml, compiler/tests-compiler/gh1559.ml, compiler/tests-compiler/gh747.ml, compiler/tests-compiler/global_deadcode.ml, compiler/tests-compiler/mutable_closure.ml, compiler/tests-compiler/tailcall.ml, compiler/tests-full/stdlib.cma.expected.js, compiler/tests-sourcemap/dune
following the previous broken attempt in #1565.
Also
- It revert the fix in https://github.com/ocsigen/js_of_ocaml/pull/1561 which is no longer needed. @rickyvetter, can you confirm the PR still works for you ?
=> Compiler: only flush the necessary env for closure 

CHANGES.md, dune-project, js_of_ocaml-tyxml.opam, lib/js_of_ocaml/dom_html.ml, lib/js_of_ocaml/dom_html.mli, lib/tyxml/tyxml_cast.ml, lib/tyxml/tyxml_cast_sigs.ml, lib/tyxml/tyxml_cast_sigs.mli
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
and
https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element
I think that I remember that `cancel` and `close` events are not well supported, but they are part of the spec.
~THIS PR DEPENDS ON CURRENT TYXML MASTER, which is unreleased right now. Would a new tyxml release be good enough for this to be merged?~
=> Dialog element support

CHANGES.md, lib/js_of_ocaml/dom_html.ml, lib/js_of_ocaml/dom_html.mli
Some annoying bug I found while trying to coerce some elt with `Html.CoerceTo.p`.
=> Lib: fix paragraph construction and coercion

CHANGES.md, compiler/lib/generate.ml
Fix bug introduced in #1567. Should fix #1579.
=> Compiler: fix parallel renaming

CHANGES.md, compiler/lib/generate.ml, compiler/lib/specialize_js.ml, compiler/lib/var_printer.ml, compiler/tests-check-prim/main.output, compiler/tests-check-prim/main.output5, compiler/tests-check-prim/unix-unix.output, compiler/tests-check-prim/unix-unix.output5, compiler/tests-check-prim/unix-win32.output, compiler/tests-check-prim/unix-win32.output5, compiler/tests-compiler/dune.inc, compiler/tests-compiler/test_string.ml, compiler/tests-full/stdlib.cma.expected.js, runtime/mlBytes.js
resurrecting https://github.com/ocsigen/js_of_ocaml/pull/977 since https://github.com/ocaml/ocaml/pull/9565 was abandoned.
=> Compiler: recognize String.concat

manual/options.wiki
Simple typo noticed in the doc
Edit: noticed the `--` on the option on this page also display as long dashes instead of two dashes
=> Fix option name for global dead code elimination

CHANGES.md, compiler/lib/javascript.ml, compiler/lib/javascript.mli, compiler/lib/js_output.ml, compiler/lib/js_parser.mly, compiler/lib/js_traverse.ml, compiler/lib/js_traverse.mli, compiler/tests-compiler/minify.ml
=> Compiler: Fix renaming for object partterns and assignment targets

CHANGES.md, compiler/lib/duplicate.ml, compiler/lib/duplicate.mli, compiler/lib/inline.ml, compiler/tests-compiler/call_gen.ml, compiler/tests-compiler/direct_calls.ml, compiler/tests-compiler/gh1320.ml, compiler/tests-compiler/inlining.ml, compiler/tests-compiler/side_effect.ml, compiler/tests-compiler/static_eval.ml, compiler/tests-full/stdlib.cma.expected.js
Should fix https://github.com/ocsigen/js_of_ocaml/issues/357
@vouillon, I've rebased an old branch of yours (`aggressive-inlining`) and changed the logic a bit so that
- it can replace the previous "simple" optimization (inlining closure of "size" one).
- it only duplicates other small closures if they call one of their arguments in tail position (this is an attempt at addressing #357)
=> Compiler: Rework inlining 

CHANGES.md, lib/gen_stubs/gen_stubs.ml, lib/js_of_ocaml/js_of_ocaml_stubs.c, lib/lwt/graphics/graphics_js_stubs.c, lib/runtime/js_of_ocaml_runtime_stubs.c
=> Runtime: abort instead of exit on unimplemented js primitives

CHANGES.md, compiler/bin-js_of_ocaml/compile.ml, compiler/lib/driver.ml, compiler/lib/linker.ml, compiler/lib/linker.mli, compiler/lib/unit_info.ml, compiler/lib/unit_info.mli, toplevel/examples/lwt_toplevel/dune, toplevel/examples/lwt_toplevel/test_lib/a.ml, toplevel/examples/lwt_toplevel/test_lib/b.ml, toplevel/examples/lwt_toplevel/test_lib/dune, toplevel/examples/lwt_toplevel/test_lib/stubs.js
Quick hack to make it possible to include some JavaScript files when compiling an OCaml library.
For now, one has to pass the `--linkall` and `--no-runtime` flags:
```
js_of_ocaml --linkall --no-runtime runtime.js library.cma
```
At the moment, the generated code uses some ECMAScript 6 features.
Trying to address https://github.com/ocsigen/js_of_ocaml/issues/1508
=> Make it possible to link runtime JavaScript file together with OCaml libraries

CHANGES.md, README.md, compiler/tests-jsoo/test_marshal.ml, manual/overview.wiki, runtime/marshal.js
Re-enable marshalling of floats that were disabled in js_of_ocaml 2.0.
This is necessary to have ocamlc compiled to js working again with OCaml 5.1 due to https://github.com/ocaml/ocaml/pull/11997.
Before this PR, one could successfully generate marshalled data containing floats that SHOULD NOT be unmarshalled with the standard runtime. I now find it better to allow marshaling floats and document that the result should not be used in native/bytecode.
=> Runtime: re-support marshaling floats

CHANGES.md, lib/js_of_ocaml/js_of_ocaml_stubs.c, lib/js_of_ocaml/typed_array.ml, lib/js_of_ocaml/typed_array.mli
This adds an API in `Typed_array` for converting uint8Array values into bytes. Because the runtime uses uint8Array internally to represent bytes, this doesn't need to copy anything. Modifying the resulting bytes will also modify the original uint8Array.
=> Add Typed_array.Bytes module

CHANGES.md, runtime/backtrace.js, runtime/jslib.js
@phated, I think this PR would fix your performance issue in https://github.com/grain-lang/grain/pull/1909
=> Runtime: record backtraces should be explicit

CHANGES.md, compiler/lib/ocaml_compiler.ml, compiler/lib/ocaml_compiler.mli, compiler/lib/unit_info.ml, compiler/tests-linkall/dune, compiler/tests-linkall/test.ml, compiler/tests-linkall/test.reference
=> Fix link of packed module with separate compilation

CHANGES.md, compiler/lib/generate.ml, compiler/tests-compiler/direct_calls.ml
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#direct_and_indirect_eval
=> Compiler: compact indirect call

compiler/tests-jsoo/dune, compiler/tests-jsoo/test_marshal.ml, compiler/tests-jsoo/test_marshal_compressed.ml
This is a better #1620: testing of Marshal with compression is enabled on 5.1.1 and higher, and tests for `Compression.compression_supported`.
=> Test marshalling compression only when enabled

lib/js_of_ocaml/dom_html.ml, runtime/jslib_js_of_ocaml.js
=> Dom_html.html_entities: move error handling to the ML side

compiler/lib/build_info.ml, compiler/lib/build_info.mli
=> Build_info/Unit_info: conversion to and from string maps

compiler/lib/driver.ml, compiler/lib/effects.ml, compiler/lib/effects.mli, compiler/lib/generate.ml, compiler/lib/generate.mli
This makes a more precise distinction between CPS calls and trampolined calls, and keeps track of both. It is used in wasm_of_ocaml to handle CPS calls.
This PR is the first in a series of PRs intending to reduce the diff between js_of_ocaml and wasm_of_ocaml, in order to merge the two repos eventually, or at least to ease integration of JSOO updates in WSOO.
=> Effects: keep track of CPS calls and distinguish CPS calls and trampolined calls

CHANGES.md, compiler/lib/js_output.ml, compiler/lib/source_map.ml, compiler/lib/source_map.mli
=> extracted from #1617

compiler/bin-js_of_ocaml/check_runtime.ml, compiler/bin-js_of_ocaml/compile.ml, compiler/bin-js_of_ocaml/link.ml, compiler/lib-dynlink/js_of_ocaml_compiler_dynlink.ml, compiler/lib/generate.ml, compiler/lib/primitive.ml
=> Generate: explicit initialization

compiler/lib/code.ml, compiler/lib/code.mli, compiler/lib/freevars.ml, compiler/lib/freevars.mli, compiler/lib/fs.ml, compiler/lib/fs.mli, compiler/lib/generate.ml, compiler/lib/generate.mli, compiler/lib/inline.ml, compiler/lib/stdlib.ml, compiler/lib/tailcall.ml
This PR consists in a number of changes in the APIs of `compiler/lib/` that @vouillon needed while developing wasm_of_ocaml.
It is best reviewed commit by commit.
=> Small changes in the internal APIs for Wasm

lib/js_of_ocaml/js_of_ocaml_stubs.c, lib/js_of_ocaml/json.ml, lib/js_of_ocaml/json.mli, lib/tests/test_json.ml, runtime/obj.js
In Wasm, some additional functions are required to output Json.
=> Runtime: implement Json output for Wasm

lib/js_of_ocaml/json.mli
See https://github.com/ocsigen/js_of_ocaml/pull/1660#discussion_r1732340382.
=> Remove unnecessary export

CHANGES.md, compiler/bin-js_of_ocaml/cmd_arg.ml, compiler/bin-js_of_ocaml/link.ml, compiler/lib/js_output.ml, compiler/lib/source_map.ml, compiler/lib/source_map.mli, compiler/tests-compiler/sourcemap.ml, compiler/tests-sourcemap/dump_sourcemap.ml
This was extracted from #1617. When linking, it was observed that parsing the mappings field of sourcemaps takes a big toll on the overall performance, and was unnecessary since the mappings are not modified.
=> Decode sourcemap mappings only when necessary

CHANGES.md, compiler/tests-jsoo/test_ints.ml, runtime/int64.js
=> Runtime: fix parsing of unsigned int64

CHANGES.md, compiler/tests-jsoo/test_channel.ml, runtime/io.js, runtime/marshal.js
should fix https://github.com/ocsigen/js_of_ocaml/issues/1668
@ejgallego can you confirm ?
=> Runtime: fix incorrect pos_in after unmarshall

compiler/lib/flow.ml, compiler/lib/global_flow.ml
This does not make much of the difference at the moment, since not many blocks are marked as immutable.
=> Take into account block mutability in flow analysis

CHANGES.md, lib/js_of_ocaml/typed_array.ml, lib/js_of_ocaml/typed_array.mli, lib/tests/test_typed_array.ml
**Note:** This PR depends on #1649 and is based on top of it. ~~The feature change consists in the last two commits.~~ edit: #1649 has been merged.
This:
- Updates the typing of `Typed_array` so that they work with the Wasm backend as well
- Adds tests for the new `Typed_array.Bytes` module.
=> Update typing of typed arrays to support Wasm, and test Typed_array.Bytes

runtime/bigarray.js, runtime/compare.js, runtime/fs_fake.js, runtime/hash.js, runtime/jslib.js, runtime/marshal.js, runtime/obj.js, runtime/parsing.js, runtime/sys.js, runtime/weak.js
https://biomejs.dev/linter/rules/use-is-array
=> runtime: use `Array.isArray()` instead of `instanceof Array`

runtime/parsing.js
spotted while working on https://github.com/ocsigen/js_of_ocaml/pull/1672
cc @smorimoto
=> Runtime: small refactoring in parsing.js

CHANGES.md, compiler/lib/code.ml, compiler/lib/code.mli, compiler/lib/dgraph.ml, compiler/lib/dgraph.mli, compiler/lib/driver.ml, compiler/lib/generate.ml, compiler/lib/global_deadcode.ml, compiler/lib/js_simpl.ml, compiler/lib/js_simpl.mli, compiler/lib/pure_fun.ml, compiler/tests-compiler/direct_calls.ml, compiler/tests-compiler/effects_toplevel.ml, compiler/tests-compiler/global_deadcode.ml, compiler/tests-full/stdlib.cma.expected.js
We now take into account of whether an instruction is in a live function or not when generating constraints, so that dead code can no longer result in making a variable live.
We also keep track of nested module.
The performance of the algorithm has been greatly improved as well.
On the `basic_website` example of Tyxml, compiled with `--opt 3`, I get the following reduction in code size:
|     | before | after | |
| ---  | ---: | ---: |  --- |
| uncompressed | 139304 | 125168 | -10% |
| gzip | 47980 | 41367 | -14% |
| bzip2 | 45298 | 38885 | -14% |
Here are the numbers regarding #1612, when compiling `with_bedrock2_fiat_crypto.byte`. For comparison, I have included an intermediate step which just optimizes the current algorithm.
| |before | optimized | after |
| -- | --: | --: | --: |
| …
=> Improved global deadcode elimination

compiler/lib/code.ml, compiler/lib/code.mli
=> Compiler: nativeInt is always 32bit

CHANGES.md, compiler/lib/linker.ml
follows #1193.
related to #1622
=> Compiler: joo_global_object is deprecated

compiler/lib/targetint.ml
=> Compiler: fix 32bit build

.github/workflows/build.yml, benchmarks/sources/ml/splay.ml, compiler/lib/stdlib.ml, compiler/lib/targetint.ml, compiler/tests-compiler/dune.inc, compiler/tests-compiler/gen-rules/gen.ml, compiler/tests-compiler/gh1051.ml, compiler/tests-compiler/pbt/test_int31.ml
Let's see how far this gets, likely we will need some extra setup but depexts got much better in Opam 2.2.
=> [ci] Add 32bit job for 4.14.2

biome.json, runtime/bigarray.js, runtime/format.js, runtime/hash.js, runtime/marshal.js, runtime/mlBytes.js, runtime/parsing.js
=> Runtime: Annotate all fall through switch case 

CHANGES.md, compiler/bin-js_of_ocaml/build_fs.ml, compiler/lib-dynlink/js_of_ocaml_compiler_dynlink.ml, compiler/lib-dynlink/js_of_ocaml_compiler_dynlink.mli, compiler/lib-dynlink/stubs.c, compiler/tests-check-prim/main.output, compiler/tests-check-prim/main.output5, compiler/tests-check-prim/unix-unix.output, compiler/tests-check-prim/unix-unix.output5, compiler/tests-check-prim/unix-win32.output, compiler/tests-check-prim/unix-win32.output5, compiler/tests-full/fs.expected.js, runtime/fs.js, runtime/stdlib.js, runtime/toplevel.js, toplevel/examples/lwt_toplevel/toplevel.ml
=> Reduce number of global names

.github/workflows/build.yml
Caveats:
- The OCaml switch in this case byte-only, so things are slow, as jsoo itself won't have a native mode
- JS ppx libs 0.17 don't really support 32bit builds, this will likely become a problem in the future (if not now actually, for example `ppx_inline_test.0.17.0` fails to build)
- jsCoq/coq-lsp works in this setup, which is IMO a great "data point" as to whether this setup is OK
p.s: Coq stops working in 5.2.0 if I pass `--enable=effects` tho, the error is `Reason: Uncaught RangeError: Maximum call stack size exceeded`, is that worth reporting?
=> [ci] Add 32bit 5.2.0 job

biome.json, runtime/fs.js, runtime/ieee_754.js, runtime/marshal.js, runtime/mlBytes.js
> Note: substr() is not part of the main ECMAScript specification — it's defined in [Annex B: Additional ECMAScript Features for Web Browsers](https://tc39.es/ecma262/multipage/additional-ecmascript-features-for-web-browsers.html), which is normative optional for non-browser runtimes. Therefore, people are advised to use the standard [String.prototype.substring()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) and [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) methods instead to make their code maximally cross-platform friendly. The [String.prototype.substring() page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring# …
=> Runtime: don't use substr

runtime/lexing.js, runtime/mlBytes.js
=> runtime: do not force array shape for bytes in lexing.js

CHANGES.md, compiler/bin-js_of_ocaml/build_fs.ml, compiler/bin-js_of_ocaml/cmd_arg.ml, compiler/bin-js_of_ocaml/cmd_arg.mli, compiler/bin-js_of_ocaml/compile.ml, compiler/bin-js_of_ocaml/link.ml, compiler/bin-jsoo_minify/jsoo_minify.ml, compiler/lib/driver.ml, compiler/lib/driver.mli, compiler/lib/js_assign.ml, compiler/lib/js_output.ml, compiler/lib/js_output.mli, compiler/lib/link_js.ml, compiler/lib/link_js.mli, compiler/lib/source_map.ml, compiler/lib/source_map.mli, compiler/tests-compiler/build_path_prefix_map.ml, compiler/tests-compiler/macro.ml, compiler/tests-compiler/sourcemap.ml, compiler/tests-compiler/util/util.ml, compiler/tests-sourcemap/dump.reference, compiler/tests-sourcemap/dump_sourcemap.ml, compiler/tests-sourcemap/dune
This has been extracted from #1617 upon @hhugo's suggestion. “Index” sourcemaps are useful to merge multiple sourcemaps at a low cost and is part of the optimization in #1617.
=> Handle composite sourcemaps

CHANGES.md, lib/js_of_ocaml/dom_html.ml, lib/js_of_ocaml/dom_html.mli, lib/tyxml/tyxml_cast.ml, lib/tyxml/tyxml_cast_sigs.ml, lib/tyxml/tyxml_cast_sigs.mli
Hello,
This PR adds the `detailsElement` and related `toggleEvent` objects.
See:
- https://html.spec.whatwg.org/multipage/interactive-elements.html#the-details-element ;
- https://html.spec.whatwg.org/multipage/indices.html#event-toggle ;
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#attributes ;
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#events .
See also these related PRs:
- [#341 in tyxml](https://github.com/ocsigen/tyxml/pull/341)
- [#806 in eliom](https://github.com/ocsigen/eliom/pull/806)
Please let me know of any issue.
Cheers,
=> Add `detailsElement` and `toggleEvent` objects.

CHANGES.md, compiler/tests-check-prim/main.output, compiler/tests-check-prim/unix-unix.output, compiler/tests-check-prim/unix-win32.output, runtime/js/prng.js
`caml_int64_of_string` is quite slow.  Move the call from the body of `caml_lxm_next` to a constant.
Making this change resulted in a 2x speedup of some code that calls `caml_lxm_next` in a tight loop.
=> precompute prng lxm constants

CHANGES.md, examples/graph_viewer/viewer_js.ml, examples/hyperbolic/hypertree.ml, examples/planet/planet.ml, lib/js_of_ocaml/dom_html.ml, lib/js_of_ocaml/dom_html.mli, lib/lwt/graphics/graphics_js.ml, toplevel/examples/lwt_toplevel/toplevel.ml
Some properties and methods have been redefined to be numbers rather than just numbers.
This partially addresses  #1719.
=> Dom_html: fix the type of some properties and methods

biome.json, runtime/js/jslib.js, runtime/js/stdlib.js, runtime/js/stdlib_modern.js, runtime/wasm/runtime.js
=> Runtime: no longer use arguments

README.md, README_wasm_of_ocaml.md
=> Doc: document mininum requirements

CHANGES.md, compiler/lib/dgraph.ml, compiler/lib/dgraph.mli, compiler/lib/global_flow.ml, compiler/tests-compiler/dune.inc, compiler/tests-compiler/gh1768.ml
We were not correctly propagating the information that a block is possibly mutated.
=> Fix global data flow analysis

CHANGES.md, examples/boulderdash/boulderdash.ml, examples/hyperbolic/hypertree.ml, lib/js_of_ocaml/dom_html.ml, lib/js_of_ocaml/dom_html.mli, lib/js_of_ocaml/file.mli, lib/js_of_ocaml/form.ml, lib/js_of_ocaml/url.ml, lib/js_of_ocaml/xmlHttpRequest.ml, lib/js_of_ocaml/xmlHttpRequest.mli, lib/lwt/lwt_xmlHttpRequest.ml, tools/ci_setup.ml, toplevel/examples/lwt_toplevel/toplevel.ml
Mostly, removed opdef for properties that are widely available.
=> Modernize a bit Dom_html

CHANGES.md, compiler/bin-js_of_ocaml/compile.ml, dune-project, js_of_ocaml-compiler.opam, runtime/js/io.js, runtime/js/parsing.js
Alternative to #1578 and #1577.
This PR requires ppx_expect and alcotest to be changed.
Because the jsoo codebase rely on ppx_expect for its tests, we have a Chicken-and-egg situation.
I can make a minor release of jsoo that would include new runtime function while keeping the existing storage mechanism.
Once jsoo is released, ppx_expect can rely on the new runtime functions.
After ppx_expect is released, we can merge this PR. 
@tkluck-janestreet, how does that sound ?
=> Don't leak channels.

runtime/wasm/effect.wat, runtime/wasm/jslib.wat, runtime/wasm/stdlib.wat, tools/ci_setup.ml
So that we can later implement `-enable use-js-string` without breaking compatibility with the Wasm runtime file of package  `zarith_stubs_js`:
- `caml_named_value` no longer assumes that strings are of type `ref $string`;
- add a function `caml_jsstring_of_substring` to be used instead of the low-level function `jsstring_of_substring`.
=> Wasm runtime changes

.github/workflows/build-wasm_of_ocaml.yml, .github/workflows/build.yml, .github/workflows/lint.yml, .gitignore, dune, tools/ci_setup.ml
Check the CI does not complain...
=> Update GitHub Actions workflows

ECMASCRIPT.md
- ~Fix the document filename~
- Link compatible tables directly
- MDN for browsers and Node.js
- Node.js official documentation for Node.js
=> Refine ECMASCRIPT.md

CHANGES.md, lib/js_of_ocaml/dom_html.ml, lib/js_of_ocaml/dom_html.mli
add other TextMetrics property https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics and comment with links
=> Add other textMetrics property

.github/workflows/build-wasm_of_ocaml.yml, .github/workflows/build.yml
Work-around a race between reinstalling mingw-w64-shims
(e.g. because of conf-pkg-config optional dep) and installing other
packages that implicitly depend on mingw-w64-shims.
=> CI: workaround opam pkg bug

.github/workflows/build-wasm_of_ocaml.yml
See https://github.com/libuv/libuv/issues/3622
=> CI: wasm tests are flaky on windows because of libuv

CHANGES.md, compiler/tests-ocaml/lib-dynarray/test.ml, runtime/js/marshal.js, runtime/wasm/marshal.wat
This brings the behavior closer to the upstream runtime
=> Runtime: fresh obj_id when un-marshaling

compiler/tests-jsoo/lib-effects-2/dune
- Copy files with expected output
- Remove duplicated env settings
- Do not run the test with wasm_of_ocaml, which does not support the double translation
=> Fix double-translation tests

CHANGES.md, compiler/tests-io/dune, compiler/tests-io/non_ascii_filenames.expected, compiler/tests-io/non_ascii_filenames.ml, runtime/js/fs.js, runtime/js/fs_fake.js, runtime/js/fs_node.js, runtime/js/io.js, runtime/js/sys.js, runtime/js/unix.js
@hhugo I'm a bit worried of making large changes right before a release. So, if you are unsure of some of the changes, I can just omit them.
=> Various runtime fixes

CHANGES.md, ECMASCRIPT.md, runtime/js/jslib_js_of_ocaml.js, runtime/js/marshal.js
This PR enhances error handling in the `caml_xmlhttprequest_create` implementation and removes the unnecessary Map polyfill to simplify the `MlObjectTable` implementation. It provides more detailed error messages when `caml_xmlhttprequest_create` fails and updates documentation to reflect the use of these APIs.
=> runtime(js): better caml_xmlhttprequest_create error handling and remove Map polyfill

CHANGES.md, ECMASCRIPT.md, runtime/js/bigarray.js, runtime/js/fs_fake.js, runtime/js/fs_node.js, runtime/js/int64.js, runtime/js/io.js, runtime/js/marshal.js, runtime/js/mlBytes.js, runtime/js/nat.js, runtime/js/sync.js
This PR updates several JavaScript runtime components to use ES6 class syntax instead of the traditional prototype-based object model. This modernization improves code readability and maintainability while aligning with current JavaScript best practices.
- Converted the classes to ES6 syntax
- Updated class inheritance patterns to use the `extends` keyword
- Replaced prototype method definitions with class methods
- Maintained all existing functionality while improving code structure
- More readable and maintainable code structure
- Better alignment with modern JavaScript development practices
- Clearer class hierarchies through explicit `extends` relationships
- Improved code organization with methods contained within class definitions
- Updated `ECMASCRIPT.md` to document ES6 class …
=> runtime(js): use es6 class

CHANGES.md, compiler/tests-jsoo/gh1845.t, runtime/js/fs_node.js
We are using fstat to test whether the file is seekable. This function  fails on standard streams under Windows with node 18 (and lower). See  https://github.com/libuv/libuv/pull/3811. So, we just assume that the   file is not seekable in case an exception is risen.
Fixes #1845
=> Fix initialization of standard streams under Windows

CHANGES.md, runtime/js/fs_node.js
This PR addresses the deprecation warning [DEP0008](https://nodejs.org/api/deprecations.html#DEP0008) by replacing direct usage of the deprecated `node:constants` module with the recommended approach of accessing constants through their respective modules.
- Replaced `require("node:constants")` with `require("node:fs").constants` in `runtime/js/fs_node.js`
- Updated code to follow Node.js best practices for accessing module-specific constants
- [Node.js Deprecation Guide (DEP0008)](https://nodejs.org/api/deprecations.html#DEP0008)
- [Node.js File System Constants](https://nodejs.org/api/fs.html#fs_file_system_flags)
=> runtime(js): update constant imports to use `node:fs` module

dune-project, js_of_ocaml-compiler.opam, js_of_ocaml-compiler.opam.template, js_of_ocaml-lwt.opam, js_of_ocaml-lwt.opam.template, js_of_ocaml-ppx.opam, js_of_ocaml-ppx.opam.template, js_of_ocaml-ppx_deriving_json.opam, js_of_ocaml-ppx_deriving_json.opam.template, js_of_ocaml-toplevel.opam, js_of_ocaml-toplevel.opam.template, js_of_ocaml-tyxml.opam, js_of_ocaml-tyxml.opam.template, js_of_ocaml.opam, js_of_ocaml.opam.template, wasm_of_ocaml-compiler.opam, wasm_of_ocaml-compiler.opam.template
fix https://github.com/ocsigen/js_of_ocaml/issues/1852
=> Misc: no subst

CHANGES.md, compiler/lib/js_traverse.ml, compiler/lib/js_traverse.mli, compiler/tests-compiler/scopes.ml
Function declarations are block-scoped, except at toplevel where they are treated like var declarations.
This fixes #1865.
=> Fix function declaration scopes in Js_traverse.rename_variable

CHANGES.md, compiler/lib/generate.ml, compiler/tests-compiler/dune.inc, compiler/tests-compiler/gh1868.ml, compiler/tests-compiler/util/util.ml
We have a pass that removes empty blocks. This can trigger an assertion failure in code generation. It is safe to remove this assertion.
This fixes #1868.
=> Fix assert failure in double translation

compiler/lib-wasm/link.ml, compiler/lib/parse_bytecode.ml, compiler/lib/unit_info.ml, compiler/lib/unit_info.mli
By @Enoumy:
> This field is semi-expensive to compute/parse and is also unused. This patch removes the computation of this field.
When linking js_of_ocaml.bc.js, the difference seems to be in the noise, however.
=> Stop parsing CRCs

CHANGES.md, lib/js_of_ocaml/dom_html.ml
For the standard location (0) we were ignoring the `code` property of the keyboard event and using the deprecated `keyCode` property instead.
=> Fix Dom_html.Keyboard_code.of_event

CHANGES.md, compiler/lib/link_js.ml, compiler/lib/stdlib.ml
This is a pair of patches by @Enoumy, in use in the internal version of JSOO at Jane Street.
=> Improve Link_js performance

compiler/bin-js_of_ocaml/compile.ml, compiler/bin-wasm_of_ocaml/preprocess.ml, compiler/lib-wasm/binaryen.ml, compiler/lib-wasm/link.ml, compiler/lib/link_js.ml, compiler/lib/parse_js.ml, compiler/lib/source_map.ml, compiler/lib/source_map.mli, compiler/lib/stdlib.ml, compiler/tests-compiler/util/util.ml, compiler/tests-sourcemap/dump_sourcemap.ml, tools/sourcemap/jsoo_sourcemap.ml, toplevel/bin/jsoo_mkcmis.ml
This PR deprecate `open_in` and `open_out` and introduces `open_in_text` and `open_out_text`.
Following the compiler warning, fix the codebase with this appropriate variant.
Also refactor code for reading lines from a file.
=> Small cleanup

benchmarks/report-jsoo-cb.config
Using `histogramref` causes the first metric to be always 1.
=> Fix current-bench benchmark config for JSOO time

CHANGES.md, ppx/ppx_js/lib_internal/ppx_js_internal.ml, ppx/ppx_js/tests/dune, ppx/ppx_js/tests/gen.mlt
We now support `function <CASES>` and `(type <TYPE>`) in object literals
and explicitly forbid polymorphic method instead of dropping part of the parsetree.
=> Ppx_js: more tests

CHANGES.md, compiler/lib-wasm/gc_target.ml, compiler/lib-wasm/generate.ml, compiler/lib-wasm/target_sig.ml, compiler/tests-wasm_of_ocaml/dune, compiler/tests-wasm_of_ocaml/gh1904.ml
A value of type `float array` is an unboxed float array, unless it is empty. The bound checking code was wrongly assuming that it was always an unboxed float array.
=> Fix bound check for empty float array

CHANGES.md, compiler/lib/effects.ml, compiler/tests-jsoo/lib-effects/dune, runtime/wasm/effect.wat
This was done in #1765 for the JavaScript runtime.
See corresponding OCaml PR ocaml/ocaml#12735
fix https://github.com/ocsigen/js_of_ocaml/issues/1779
=> Wasm runtime: make resuming continuations more efficient

compiler/lib-wasm/code_generation.ml, compiler/lib-wasm/curry.ml, compiler/lib-wasm/gc_target.ml, compiler/lib-wasm/generate.ml, compiler/lib-wasm/initialize_locals.ml, compiler/lib-wasm/tail_call.ml, compiler/lib-wasm/wasm_ast.ml, compiler/lib-wasm/wasm_link.ml, compiler/lib-wasm/wasm_output.ml, compiler/lib-wasm/wat_output.ml
Plus small type-related fix in the Wasm linker
=> More extensive Wasm AST

CHANGES.md, compiler/lib-wasm/gc_target.ml, compiler/lib-wasm/generate.ml, compiler/lib-wasm/target_sig.ml, compiler/lib-wasm/wat_output.ml, compiler/tests-compiler/test_string.ml, runtime/js/compare.js, runtime/js/ieee_754.js, runtime/js/ints.js, runtime/js/mlBytes.js, runtime/js/prng.js, runtime/wasm/float.wat
- evaluate statically more primitives
- add some missing `const` annotations in the JavaScript runtime
- provide mutability information for primitives handled internally when generating Wasm code
=> Optimization of primitives: some improvements

compiler/lib/structure.ml
`Structure.is_merge_node` is called for many successors of a node and was linear in the number of predecessor, which could yield a quadratic behavior during Wasm code generation, especially after #1934 which removes some intermediate blocks (see [Fiat-Crypto benchmark](https://bench.ci.dev/ocsigen/js_of_ocaml/pull/1934/base/master/benchmark/Wasm_of_ocaml?worker=autumn&image=bench.Dockerfile)).
=> Fix performance issue with Structure.is_merge_node

CHANGES.md, compiler/lib/driver.ml, compiler/lib/flow.ml, compiler/lib/flow.mli, compiler/lib/inline.ml, compiler/lib/specialize_js.ml, compiler/lib/specialize_js.mli, compiler/lib/tailcall.ml, compiler/tests-compiler/double-translation/effects_continuations.ml, compiler/tests-compiler/double-translation/effects_exceptions.ml, compiler/tests-compiler/effects_continuations.ml, compiler/tests-compiler/effects_exceptions.ml, compiler/tests-compiler/eliminate_exception_handler.ml, compiler/tests-compiler/exceptions.ml, compiler/tests-compiler/gh1007.ml, compiler/tests-compiler/gh1868.ml, compiler/tests-compiler/global_deadcode.ml, compiler/tests-compiler/loops.ml, compiler/tests-compiler/match_with_exn.ml, compiler/tests-compiler/tailcall.ml, compiler/tests-full/stdlib.cma.expected.js
We introduce an intermediate block at the beginning of the closure (if necessary) and jump back to it when we see a tailcall.
With this, we can:
- remove the "skip_param" argument from "Flow.f"
- simplify the O3 profile. Well, O3 is now identical to O2
=> Compiler: make tailcall optim more robust

README_wasm_of_ocaml.md, manual/menu.wiki, manual/wasm_overview.wiki
This proposes to update wasm_of_ocaml documentation in several ways:
- Usage and installation instructions are removed from `README_wasm_of_ocaml.md` and a pointer to the relevant manual page is added instead. Several of these instructions were out of date. Similarly, the “Implementation status” section is removed in favor of the clearer “Supported features” section in the linked manual page.
- In the menu, the link “Binding JS libraries” is renamed to “Writing Wasm primitives”, which is the actual title of the page, and seems clearer to me. Also, a duplicate link is removed.
- In the manual, some superfluous indentations are removed (unless I’m missing something about the wikidoc format) and a subsection is added with a few explanations about primitives, and a link to the relevant page.
=> Update and clarify wasm_of_ocaml documentation

CHANGES.md, compiler/bin-js_of_ocaml/cmd_arg.ml, compiler/bin-js_of_ocaml/cmd_arg.mli, compiler/bin-js_of_ocaml/compile.ml, compiler/bin-js_of_ocaml/link.ml, compiler/lib/link_js.ml, compiler/lib/link_js.mli, compiler/lib/source_map.ml, compiler/lib/source_map.mli, compiler/tests-jsoo/empty_sourcemap.t
This patch implements the `--empty-sourcemap` flag. It is used to generate an empty sourcemap, which is cheap. Sometimes application authors would like the cheapness of not building sourcemap files to speed up development iterations, but their build pipelines do not handle the case where `.map` files are not produced at all (think, e.g., custom Dune rules depending on `.map` files and passing them to a bundler). In such cases, they would like to still generate the empty `.map` files.
cc @rickyvetter
=> Add flag `--empty-sourcemap`

compiler/lib/code.ml, compiler/lib/code.mli, compiler/lib/deadcode.ml, compiler/lib/driver.ml, compiler/lib/eval.ml, compiler/lib/flow.ml, compiler/lib/inline.ml, compiler/lib/phisimpl.ml, compiler/lib/specialize.ml, compiler/lib/specialize_js.ml, compiler/lib/tailcall.ml, dune-workspace
Following https://github.com/ocsigen/js_of_ocaml/pull/1950:
- This PR adds debug stats to other optimization passes.
- It also introduces some debug information for the stats logic themselves. We check that, for a given pass, if we report  0 updates, the program is not modified.
~~We also speedup the specialize pass in https://github.com/ocsigen/js_of_ocaml/commit/fe85720aed23663abdb9975e8c7cbf8869e0b09a~~
=> Compiler: add more debug stats

CHANGES.md, compiler/lib/eval.ml, compiler/lib/flow.ml, compiler/lib/flow.mli, compiler/lib/specialize_js.ml
Whether two constants should be considered equal depends on the context in which they are used.
=> Flow.the_const_of: allow to use different comparison functions

CHANGES.md, compiler/lib/deadcode.ml, compiler/lib/deadcode.mli, compiler/lib/driver.ml, compiler/tests-compiler/gh1768.ml, compiler/tests-compiler/lambda_lifting.ml, compiler/tests-full/stdlib.cma.expected.js
On top of #1962, this PR adds an optimization to merged blocks that are not necessary for control_flow.
When tried on the lwt toplevel, the first pass merges 34493 blocks out of  124770.
This should hopefully speedup others passes.
=> Compiler: Merge blocks

CHANGES.md, compiler/lib/js_assign.ml
This PR removes a bottleneck in the coloring algorithm and significantly speedup the pass.
=> Compiler: speedup coloring

compiler/lib/code.ml, compiler/lib/code.mli, compiler/lib/driver.ml, compiler/lib/parse_bytecode.ml, compiler/lib/stdlib.ml
Blocks `Addr.t` are sparse in a program. This can be wasteful when using bitset to encode visited blocks.
The PR propose to "compact" `Addr.t` in a program if needed.
=> Compiler: compact program Addr.t

compiler/lib/code.ml, compiler/lib/code.mli, compiler/lib/deadcode.ml, compiler/lib/duplicate.ml, compiler/lib/duplicate.mli, compiler/lib/effects.ml, compiler/lib/eval.ml, compiler/lib/generate_closure.ml, compiler/lib/global_deadcode.ml, compiler/lib/inline.ml, compiler/lib/phisimpl.ml, compiler/lib/specialize.ml, compiler/lib/specialize_js.ml, compiler/lib/subst.ml, compiler/lib/tailcall.ml
The PR fixes `inline.ml` to respect the invariant. includes a prefix of #1935  and borrow its cleanup logic.
The goal is to merge this PR before #1935.
=> More check points for code.invariant. 

benchmarks/sources/js/binary_trees.js, benchmarks/sources/js/fft.js, benchmarks/sources/js/raytrace.js, benchmarks/sources/ml/binary_trees.ml, benchmarks/sources/ml/fft.ml, benchmarks/sources/ml/quicksort.ml, benchmarks/sources/ml/raytrace.ml, benchmarks/sources/ml/soli.ml
Some benchmarks terminate very fast and are very noisy due to startup overhead. The PR make soli, binary_trees and fft do more work so that take in the order of a second to finish.
=> Adjust some microbenmarks

runtime/wasm/jsstring.wat, runtime/wasm/runtime.js
For compatibility with Firefox which does not allow additional functions in builtin modules.
=> Wasm runtime: move JavaString hash function from wasm:js-string to bindings

benchmarks/benchmark-fiat-crypto/Makefile, compiler/bin-wasm_of_ocaml/compile.ml, compiler/lib-wasm/generate.ml, compiler/lib-wasm/generate.mli
This is faster to write a binary file, and then for binaryen to parse a binary file.
We still output a Wasm text file when source maps are enabled (we don't yet supported writing a source map file together with a Wasm binary module) or when `--debug wat` is set.
=> Output a Wasm binary module rather than a text file when possible

CHANGES.md, benchmarks/benchmark-fiat-crypto/Makefile, compiler/bin-wasm_of_ocaml/compile.ml, compiler/lib-wasm/binaryen.ml, compiler/lib-wasm/binaryen.mli, compiler/lib-wasm/generate.ml, compiler/lib-wasm/generate.mli, compiler/lib-wasm/link.ml, compiler/lib-wasm/wasm_output.ml, compiler/lib-wasm/wasm_output.mli, compiler/lib-wasm/wat_preprocess.ml, compiler/lib/source_map.ml, compiler/lib/source_map.mli, compiler/tests-jsoo/empty_sourcemap.t
=> Always output a Wasm binary module rather than a text file

compiler/lib/lambda_lifting.ml, compiler/lib/specialize_js.ml, dune
We now check invariants in the CI
=> More invariant checks

CHANGES.md, compiler/lib-wasm/code_generation.ml, compiler/lib-wasm/generate.ml, compiler/lib-wasm/initialize_locals.ml, compiler/lib-wasm/initialize_locals.mli, compiler/lib-wasm/target_sig.ml
This refines the type of locals based on the expression they are initialized with. The main motivation for this is that the environment types get refined as well, which binaryen is not able to do. In turn, some casts become unnecessary. On `ocamlc.byte`, we get the following number of casts:
| Before | After
|-|-
| 37949 | 35553
=> Use more precise types in function environments

.github/workflows/build-wasm_of_ocaml.yml, bench.Dockerfile, runtime/wasm/bigstring.wat, tools/ci_setup.ml
close https://github.com/ocsigen/js_of_ocaml/issues/2035
=> Update Jane Street tests

CHANGES.md, compiler/lib/generate.ml
Get rid of the quadratic behavior for expression queue when generate js code.
Here are speedups for the code generation pass:
- fiat-crypto -60% 
- ocamlc -14%
- partial-render-table -47%
=> Faster queue

compiler/lib/reserved.ml, compiler/tests-full/stdlib.cma.expected.js
Some where reserved as future keywords up to ECMAScript 3 and are no longer reserved.
The keyword `this` occurred twice.
=> Update list of reserved keywords

CHANGES.md, compiler/lib-wasm/call_graph_analysis.ml, compiler/lib-wasm/call_graph_analysis.mli, compiler/lib-wasm/gc_target.ml, compiler/lib-wasm/generate.ml, compiler/lib-wasm/target_sig.ml, compiler/lib-wasm/typing.ml, runtime/wasm/effect.wat, runtime/wasm/obj.wat
This reduces the amount of memory allocated. But I think this also allows Binaryen to make more optimizations, since it becomes clear that the function is only called from known places.
=> Closure optimization: omit code pointer when not used

runtime/wasm/backtrace.wat, runtime/wasm/bigarray.wat, runtime/wasm/bigstring.wat, runtime/wasm/effect.wat, runtime/wasm/fs.wat, runtime/wasm/io.wat, runtime/wasm/marshal.wat, runtime/wasm/stdlib.wat, runtime/wasm/sys.wat, runtime/wasm/unix.wat, runtime/wasm/weak.wat
Some code reordering and small changes to make #1831 shorter.
=> Wasm runtime: clean-up
