- doc/manual/src/menu.wiki
There were two links to the hyperbolic tree example
> remove duplicate link

- compiler/inline.ml
Fix https://github.com/ocsigen/js_of_ocaml/issues/278 .
> Inline identity function.

- lib/xmlHttpRequest.ml
- lib/xmlHttpRequest.mli
Useful for PUT or DELETE request.
> Add an optional parameter to set the method for a XHR request.

- lib/tyxml/tyxml_js.mli
Add references to the Tyxml project and give an example of use.
> Documentation for Tyxml_js

- runtime/Makefile
- runtime/polyfill/classlist.js
- runtime/polyfill/json2.js
As stated in the current json.js (2011-02-23), this file has been superceded by json2.js. Use this newer polyfill (2015-05-03) from https://github.com/douglascrockford/JSON-js.
Update also the classlist polyfill with the latest version (2015-03-12) from https://github.com/eligrey/classList.js/.
> Update vendors polyfills

- lib/dom_html.ml
- lib/dom_html.mli
> Lib: add getElementsByClassName

- lib/tyxml/tyxml_cast.ml
- lib/tyxml/tyxml_cast_sigs.mli
See https://github.com/ocsigen/tyxml/pull/79
> Add of_main function for <main> tag

- lib/.depend
- lib/Makefile
- lib/geolocation.ml
- lib/geolocation.mli
This is a proposal for a binding to Geolocation API. Regarding the code:
- May be the `geolocation` object should be added to the current `navigator` object attributes?
- The last two parameters (for the error function and for the options) of `getCurrentPosition` and `watchPosition` should be optional. I don't know how to specify this?
> Geolocation API: http://www.w3.org/TR/geolocation-API/

- doc/api/index
- lib/geolocation.mli
- Fix doc formatting
- Add geolocation module in index
> Documentation for geolocation module

- compiler/generate.ml
- compiler/parse_bytecode.ml
This is just a quick-fix that we should fix before/when we address https://github.com/ocsigen/js_of_ocaml/issues/384
> Compiler: attempt to fix match_with_exn

- lib/ppx/ppx_js.cppo.ml
- lib/syntax/pa_js.ml
- tests/Makefile
- tests/camlp4/object_litteral.expected
- tests/camlp4/object_litteral.ml
- tests/ppx/object_litteral.expected
- tests/ppx/object_litteral.ml
@Drup: do you want to do more than this small fix ? https://github.com/ocsigen/js_of_ocaml/issues/428
> Syntax: object litteral, preprocess prop and meth name

- lib/dom_html.ml
- lib/dom_html.mli
https://developer.mozilla.org/fr/docs/Web/API/Window/getComputedStyle
> Added window.getComputedStyle function.

- lib/dom_html.ml
- lib/dom_html.mli
While working with blobs and canvas, I needed some extra methods in js_of_ocaml. 
https://developer.mozilla.org/en-US/docs/Web/API/Window/URL
> Blob and URL

- lib/lwt_js_events.ml
- lib/lwt_js_events.mli
fix https://github.com/ocsigen/js_of_ocaml/issues/418
> Lib: transitionends

- compiler/compileArg.ml
- compiler/compileArg.mli
- compiler/driver.ml
- compiler/eval.ml
- compiler/eval.mli
- compiler/inline.ml
- compiler/jsoo_compile.ml
- runtime/mlString.js
- runtime/stdlib.js
- static evaluation of Sys.getenv
- inline simple functions (refine simple function detection)
- drop exception handler if body cannot raise
> More inlining and static evaluation

- runtime/stdlib.js
see https://github.com/ocaml/ocaml/commit/6c3a01bb7c6aade980ce132b7aebe5f028f8f669
> provide `backend_type` support in ocaml 4.04

- lib/dom_html.ml
- lib/dom_html.mli
This reverts commit 0d56d33759cf079350b2c85600c9fea6ca87fb84.
Duplicate of 4229e4b8178069d73cc646c7ce203b41736712b9.
> Revert "Added selection{Start,Stop} method to Dom_html.textAreaElement."

- lib/dom_html.ml
- lib/dom_html.mli
See http://www.w3schools.com/tags/tag_link.asp
> Dom_html: add crossorigin to linkElement. 

- lib/dom_html.ml
- lib/dom_html.mli
https://developer.mozilla.org/fr/docs/Web/CSS/transform
> Added transform to cssStyleDeclaration.

- lib/dom_html.ml
- lib/dom_html.mli
- lib/tyxml/tyxml_js.ml
Add wrapper modules that extract useful keyboard information from key events. Performs `keyCode` to `code` normalization.
> Fix keyboard events

- doc/Makefile
- examples/Makefile.common
- lib/META
- lib/Makefile
- opam
Fixes #516 . I may have missed something.
> Depend on uchar

- doc/manual/src/camlp4.wiki
- lib/Makefile
- lib/ppx/ppx_js.cppo.ml
- lib/ppx/ppx_js.ml
- lib/ppx/ppx_js.mli
- tests/ppx/meth.expected
- tests/ppx/meth.ml
- tests/ppx/object_litteral.ml
- tests/ppx/prop.expected
- tests/ppx/write_prop.expected
It should provide better merlin support.
> Import new ppx scheme from let-def

- compiler/generate_closure.ml
To be compiled on https://ci.inria.fr/ocsigen/
regression introduced by https://github.com/ocsigen/js_of_ocaml/pull/467
> Compiler: fix #531

- lib/dom_html.ml
- lib/dom_html.mli
> windo##open_ returns possibly null value

- lib/ppx/ppx_deriving_json.cppo.ml
Fixes #552 with the solution suggested by @Drup. CC @vouillon
> ppx_deriving_json: monomorphic converters for poly variants

- Makefile.filelist
- compiler/Makefile
- compiler/lib/pseudoFs.ml
- compiler/lib/reserved.ml
- examples/boulderdash/boulderdash.ml
- examples/graph_viewer/viewer_js.ml
- examples/hyperbolic/hypertree.ml
- examples/webgl/webgldemo.ml
- jsoo_tools/jsoo_mkcmis.ml
- lib/sys_js.ml
- lib/sys_js.mli
- lib/toplevel/jsooTop.ml
- runtime/fs.js
- runtime/fs_fake.js
- runtime/fs_node.js
- runtime/io.js
- runtime/jslib.js
- runtime/md5.js
- runtime/stdlib.js
- runtime/weak.js
- toplevel/Makefile
- toplevel/toplevel.cppo.ml
This brings better compatibility with nodejs.
> Rework the filesystem layer in js_of_ocaml

- lib/dom_html.ml
- lib/dom_html.mli
https://developer.mozilla.org/en-US/docs/Web/API/AnimationEvent
> Added animation events.

- lib/lwt/lwt_xmlHttpRequest.ml
- lib/lwt/lwt_xmlHttpRequest.mli
rebased version of https://github.com/ocsigen/js_of_ocaml/pull/301
cc @pveber 
I'm considering this PR for js_of_ocaml.3.0
> Lib: XmlHttpRequest, API change for perform functions. (rebased)

- doc/manual/src/rev-bindings.wiki
See #580. The Camlp4 command has already been fixed. While at it, I couldn't stop myself from nitpicking on the wiki page :).
> Fix syntax in rev-binding wiki page

- lib/jstable.ml
- lib/jstable.mli
Which apparently was forgotten?
> Addition of Jstable.delete

- examples/README.md
* Adds a readme to the examples directory which informs users how to
build the projects using jbuilder.
> Adds readme to examples directory

- js_of_ocaml-ppx.opam
- ppx/ppx_deriving_json/lib/ppx_deriving_json.cppo.ml
> ppx: fix build with ppx_deriving.4.2.1

- compiler/compileArg.ml
- compiler/compileArg.mli
- compiler/js_of_ocaml.ml
- compiler/lib/driver.ml
- compiler/lib/driver.mli
@cpitclaudel, this is a quick attempt at addressing https://github.com/ocsigen/js_of_ocaml/issues/599.
> Compiler: fix #599

- META.js_of_ocaml-ppx.template
- js_of_ocaml-ppx_deriving_json.opam
- ppx/ppx_deriving_json/lib/jbuild
- ppx/ppx_deriving_json/tests/jbuild
@hhugo as we've discussed. The test suite fails for me (but it also fails on master).
> Split [@@deriving json] into own pacakge

- doc/manual/src/ppx.wiki
- ppx/ppx_js/lib_internal/ppx_js_internal.ml
- ppx/ppx_js/tests/jbuild
- ppx/ppx_js/tests/ppx.mlt
> ppx: support for optdef_prop, writeonly_prop, ..

- lib/dom_html.ml
- lib/dom_html.mli
- lib/lwt/lwt_js_events.ml
- lib/lwt/lwt_js_events.mli
See https://html.spec.whatwg.org/multipage/media.html#mediaevents
> Added media events support.

- compiler/compileArg.ml
- js_of_ocaml-compiler.opam
.. even if it is.
\cc @rgrinberg 
@alainfrisch, would that cause any problem to you ?
> Opam: make yojson non optional ..

- dune-project
- lib/dune
Fixes https://github.com/janestreet/incr_dom/issues/5
Fixes https://github.com/janestreet/virtual_dom/issues/3
> Enable dune wrapped in transition mode

- compiler/lib/eval.ml
- compiler/tests/expect_tests/static_eval.ml
- compiler/tests/expect_tests/util.ml
- compiler/tests/expect_tests/util.mli
fix https://github.com/ocsigen/js_of_ocaml/issues/769
> Fix: static eval of String.get

- compiler/tests/expect_tests/lazy.ml
- compiler/tests/expect_tests/util.ml
- compiler/tests/expect_tests/util.mli
- runtime/stdlib.js
> Test compilation of lazy values

- toplevel/bin/dune
> Install: fix install on windows

- ppx/ppx_js/lib/dune
- ppx/ppx_js/lib/ppx_js.mli
- ppx/ppx_js/lib_internal/dune
- ppx/ppx_js/lib_internal/ppx_js_internal.ml
- ppx/ppx_js/lib_internal/ppx_js_internal.mli
- ppx/ppx_js/tests/main.ml
- toplevel/examples/lwt_toplevel/ppx_enabled.ml.in
One https://github.com/ocaml-ppx/ppx_tools_versioned/issues/13 is resolved
> Misc: bump ast used in ppx to 4.07

- ppx/ppx_deriving_json/lib/ppx_deriving_json.ml
- ppx/ppx_deriving_json/lib/ppx_deriving_json.mli
> Fix ppx_deriving_json

- manual/separate-compilation.wiki
This reverts commit 0ff280baecbf39c6567225eecd8dc76e0ab4e0b4.
fix #668
> Doc: document separate compilation (close #668)

- runtime/ieee_754.js
Added `caml_round_float` function to achieve compatibility with OCaml 4.08
> added `caml_round_float` function

- CHANGES.md
- lib/lwt/lwt_js_events.mli
- toplevel/examples/lwt_toplevel/examples.ml
see https://github.com/ocsigen/lwt/issues/603
> lib: val async : (unit -> unit Lwt.t)

- runtime/stdlib.js
> Runtime: add caml_obj_with_tag

- compiler/js_of_ocaml.ml
- compiler/jsoo_fs.ml
- compiler/lib/driver.mli
- compiler/lib/generate.ml
- compiler/lib/generate.mli
- compiler/lib/parse_bytecode.ml
- compiler/lib/parse_bytecode.mli
- compiler/lib/stdlib.ml
- toplevel/bin/jsoo_mkcmis.ml
- toplevel/examples/lwt_toplevel/dune
Should fix #818.
On my machine, toplevel creation when from ~52s to ~17s
cc @dbuenzli
> Speedup toplevel creation 

- compiler/lib/parse_bytecode.ml
https://github.com/ocaml/num/pull/16 has been merged. We now need a official release on opam
> Compiler: remove num hack

- lib/js_of_ocaml/dom_html.ml
- lib/js_of_ocaml/dom_html.mli
Add support for the following Element method
https://developer.mozilla.org/en-US/docs/Web/API/Element/closest
> Add closest method to element

- runtime/fs.js
> Runtime: fix pseudo fs initialization

- CHANGES.md
- compiler/lib/generate.ml
- compiler/tests/match_with_exn.ml
- compiler/tests/variable_declaration_output.ml
following the comment from @jordwalke https://github.com/ocsigen/js_of_ocaml/issues/945#issuecomment-568400492
> Compiler: change compilation scheme for branches

- compiler/tests-jsoo/test_rec_mod.ml
- runtime/internalMod.js
see https://github.com/ocaml/ocaml/pull/9497
> Runtime: fix camlinternalMod, following ocaml #9497

- compiler/lib/parse_bytecode.ml
Following https://github.com/ocaml/ocaml/pull/9619
> Compiler: prepare parse_bytecode for OCaml 4.12

- examples/separate_compilation/dune
- manual/separate-compilation.wiki
fix #1033 
fix in dune https://github.com/ocaml/dune/pull/3626
> Doc: fix documentation on separate compilation

- runtime/io.js
- runtime/sys.js
> Runtime: add missing primitives

- lib/js_of_ocaml/dom_html.ml
- lib/js_of_ocaml/dom_html.mli
https://developer.mozilla.org/en-US/docs/Web/API/Navigator
> Add Navigator.{vendor,maxTouchPoints}

- manual/install.wiki
It's a silly one, but worth fixing IMO.
> Fix linking in manual

- compiler/lib/stdlib.ml
> Compiler: make List.append tailrec

- CHANGES.md
- benchmarks/sources/js/loop.js
- compiler/lib/reserved.ml
- compiler/tests-check-prim/output
- compiler/tests-compiler/sys_fs.ml
- runtime/dynlink.js
- runtime/fs.js
- runtime/fs_fake.js
- runtime/fs_node.js
- runtime/hash.js
- runtime/marshal.js
- runtime/mlBytes.js
- runtime/obj.js
- runtime/str.js
- runtime/sys.js
- runtime/unix.js
- tools/format-js.sh
fix #1109 
and reformat all js files
> Runtime: add mkdir and rmdir support

- runtime/sys.js
> Runtime:  fix Sys.cygwin

- CHANGES.md
- runtime/fs.js
- runtime/unix.js
replace #1140 and should remove the need for the last jsoo hack in grain (https://github.com/grain-lang/grain/pull/922)
> Mount windows drives automatically 

- compiler/lib/dgraph.ml
- compiler/lib/generate.ml
- compiler/lib/js_assign.ml
- compiler/lib/ocaml_compiler.ml
- compiler/lib/parse_bytecode.ml
- compiler/lib/strongly_connected_components.ml
- compiler/tests-jsoo/test_marshal.ml
- dune
- tools/version/dune
- tools/version/gen/dune
- tools/version/gen/gen.ml
> Some small cleanup

- CHANGES.md
- compiler/lib/generate_closure.ml
- compiler/tests-compiler/tailcall.ml
fix #665 
@cpitclaudel, would you like to review this ?
> Compiler: optimize for tc_depth=0

- compiler/lib/stdlib.ml
> Compiler: make sure we don't use physical equality by mistake

- README.md
> Doc: fix links to toplevels

- .github/workflows/build.yml
- manual/dune
- manual/dune.inc
- manual/gen_dune_inc.ml
>  Automatically update the wikidoc branch when pushing to master

- CHANGES.md
- lib/js_of_ocaml/dom_html.ml
- lib/js_of_ocaml/dom_html.mli
> Lib: make window.{inner,outer}{Width,Height} non-optional

- CHANGES.md
- compiler/lib/js_traverse.ml
fix https://github.com/ocsigen/js_of_ocaml/issues/1247
> Compiler: fix rewriter bug

- lib/js_of_ocaml/performanceObserver.ml
- lib/js_of_ocaml/performanceObserver.mli
The PR that added these files forgot to include licenses at the top. For
the sake of consistency with all the other files, I've added the license
info.
> Misc: add missing licenses to a couple files

- runtime/fs.js
> Runtime: fix 1260

- toplevel/examples/lwt_toplevel/dune
after https://github.com/ocaml/opam-repository/pull/21309 lands
> Misc: clean up after reactiveData.3.0

- CHANGES.md
- examples/test_wheel/dune
- examples/test_wheel/index.html
- examples/test_wheel/test_wheel.ml
- lib/js_of_ocaml/dom_html.ml
- lib/js_of_ocaml/dom_html.mli
- lib/lwt/lwt_js_events.ml
- lib/lwt/lwt_js_events.mli
> Lib: wheel event binding

- CHANGES.md
- js_of_ocaml-compiler.opam
- js_of_ocaml-compiler.opam.template
- js_of_ocaml-lwt.opam
- js_of_ocaml-lwt.opam.template
- js_of_ocaml-ppx.opam
- js_of_ocaml-ppx.opam.template
- js_of_ocaml-ppx_deriving_json.opam
- js_of_ocaml-ppx_deriving_json.opam.template
- js_of_ocaml-toplevel.opam
- js_of_ocaml-toplevel.opam.template
- js_of_ocaml-tyxml.opam
- js_of_ocaml-tyxml.opam.template
- js_of_ocaml.opam
- js_of_ocaml.opam.template
> Misc: update build instruction

- CHANGES.md
- runtime/fs_node.js
- runtime/io.js
- runtime/sys.js
- runtime/unix.js
- toplevel/examples/lwt_toplevel/dune
> Runtime: no require with target-env browser

- CHANGES.md
- lib/js_of_ocaml/js.ml
- lib/js_of_ocaml/js.mli
This commit adds support for Unicode normalization.
> Lib: add normalize in js_string (ES6)

- CHANGES.md
- ppx/ppx_deriving_json/lib/ppx_deriving_json.ml
- ppx/ppx_deriving_json/tests/gen.mlt
- ppx/ppx_deriving_json/tests/ppx.mlt
~~This a rebase of an old branch by @vasilisp~~
> Fix ppx_deriving_json with nested polymorphic variant 

- lib/runtime/dune
- lib/runtime/jsoo_runtime.ml
fix https://github.com/ocsigen/js_of_ocaml/issues/1236
> Lib: add Jsoo_runtime.Sys.version

- CHANGES.md
- compiler/lib/generate.ml
- compiler/tests-compiler/util/util.ml
- runtime/gc.js
also
- fix runtime wrt `Gc.finalize_last`
- improve `--debug gen`
- improve error reporting for test-compiler
> Compiler: small refactoring

- compiler/lib/js_assign.ml
- compiler/lib/js_output.ml
I have found this useful to debug escaping variables
> Js_assign: add debugging code

- CHANGES.md
- compiler/lib/generate.ml
- compiler/tests-compiler/cond.ml
- compiler/tests-compiler/effects_continuations.ml
- compiler/tests-compiler/effects_exceptions.ml
- compiler/tests-compiler/exceptions.ml
- compiler/tests-compiler/gh1354.ml
- compiler/tests-compiler/lazy.ml
- compiler/tests-compiler/loops.ml
- compiler/tests-compiler/match_with_exn.ml
- compiler/tests-compiler/variable_declaration_output.ml
> Compiler: cleanup compilation of try-catch 

- compiler/lib-runtime-files/gen/gen.ml
This reverts commit 2b128ff810c77a62dec234991e74392cc60938b4.
> Fix 1402 for windows

- compiler/lib/generate.ml
> Compiler: replace some assert by proper errors

- CHANGES.md
- lib/js_of_ocaml/dom_html.ml
- lib/js_of_ocaml/dom_html.mli
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState
> support getModifierState in keyboard events

- compiler/tests-jsoo/dune
- compiler/tests-jsoo/flush_stubs.c
- compiler/tests-jsoo/runtime.js
- compiler/tests-jsoo/test_parsing.ml
https://github.com/ocaml/ocaml/pull/12046
> Tests: reenable some test

- CHANGES.md
- compiler/bin-js_of_ocaml/link.ml
- compiler/lib/build_info.ml
- compiler/lib/build_info.mli
- compiler/lib/link_js.ml
- compiler/lib/link_js.mli
This is useful to achieve better incrementatlity during sepearate compilation.
> Compiler: allow to link cmo.js into a cma.js

- compiler/lib/generate.ml
Small refactoring generated while working on 1496, extracted here so that 1496 is easier to review.
> Prepare for 1496

- CHANGES.md
- compiler/lib-dynlink/dune
- compiler/lib-dynlink/js_of_ocaml_compiler_dynlink.ml
- compiler/lib-dynlink/stubs.c
- compiler/lib/ocaml_compiler.ml
- compiler/lib/ocaml_compiler.mli
- compiler/lib/parse_bytecode.ml
- runtime/stdlib.js
- runtime/toplevel.js
Following https://github.com/ocaml/ocaml/pull/12599
> Compiler: Fix for OCaml  12599

- compiler/bin-js_of_ocaml/info.ml
- compiler/bin-jsoo_minify/cmd_arg.ml
- compiler/lib/base64.mli
- compiler/lib/build_info.ml
- tools/version/dune
- tools/version/gen/gen.ml
> Fix version report

- CHANGES.md
- compiler/lib/parse_bytecode.ml
- compiler/tests-compiler/dune.inc
- compiler/tests-compiler/gh1599.ml
> Compiler: fix stack compatibility check (instroduced in #1523)

- compiler/lib/link_js.ml
- compiler/lib/parse_bytecode.ml
- compiler/lib/parse_bytecode.mli
- compiler/lib/pseudo_fs.ml
- compiler/lib/stdlib.ml
- compiler/tests-toplevel/dune
- compiler/tests-toplevel/test_toplevel.ml
- compiler/tests-toplevel/test_toplevel.reference
- toplevel/examples/lwt_toplevel/dune
fix https://github.com/ocsigen/js_of_ocaml/issues/1628
> Fix missing primitives in toplevel + separate compilation

- compiler/lib/reserved.ml
> Compiler: mark TextEncoder as reserved

- CHANGES.md
- compiler/tests-dynlink-js/dune
- compiler/tests-dynlink-js/effects_flags.ml
- compiler/tests-dynlink-js/main.ml
- compiler/tests-dynlink-js/main.out.expected
- compiler/tests-dynlink-js/plugin2a.ml
- compiler/tests-dynlink-js/plugin2b.ml
- runtime/stdlib.js
> Runtime: allow dynlink of precompiled js with separate compilation

- biome.json
- runtime/bigarray.js
- runtime/compare.js
- runtime/fs.js
- runtime/graphics.js
- runtime/ieee_754.js
- runtime/jslib_js_of_ocaml.js
- runtime/nat.js
- runtime/unix.js
- runtime/zstd.js
All of these fixes are very general, independent of the JS runtime version.
> Runtime: safe fixes

- biome.json
- runtime/mlBytes.js
It makes the code a bit easier to read
@vouillon, can you review this ?
> Runtime: switch default case come last

- biome.json
- runtime/bigarray.js
- runtime/compare.js
- runtime/ieee_754.js
@vouillon, I wouldn't mind another pair of eyes on this one, trivial, yet, easy to get wrong.
> Runtime: explicit isNaN check

- compiler/bin-js_of_ocaml/compile.ml
- compiler/lib/code.ml
- compiler/lib/code.mli
- compiler/lib/deadcode.ml
- compiler/lib/duplicate.ml
- compiler/lib/effects.ml
- compiler/lib/eval.ml
- compiler/lib/flow.ml
- compiler/lib/freevars.ml
- compiler/lib/generate.ml
- compiler/lib/generate_closure.ml
- compiler/lib/global_deadcode.ml
- compiler/lib/global_flow.ml
- compiler/lib/inline.ml
- compiler/lib/lambda_lifting.ml
- compiler/lib/parse_bytecode.ml
- compiler/lib/partial_cps_analysis.ml
- compiler/lib/phisimpl.ml
- compiler/lib/pseudo_fs.ml
- compiler/lib/pseudo_fs.mli
- compiler/lib/pure_fun.ml
- compiler/lib/specialize.ml
- compiler/lib/specialize_js.ml
- compiler/lib/structure.ml
- compiler/lib/subst.ml
- compiler/lib/subst.mli
- compiler/lib/tailcall.ml
To save some rebasing work, this should probably be merged after #1461.
> Remove location from instructions

- .github/workflows/build-wasm_of_ocaml.yml
- .github/workflows/build.yml
If no version is specified, it always retrieves the latest version.
> ci: use latest binaryen

- compiler/lib/dune
- dune-project
- https://github.com/ocaml/dune/pull/9512
> dune: update menhir extension to 3.0

- .gitattributes
Check the CI does not complain...
> Remove unused files

- .github/workflows/build-wasm_of_ocaml.yml
- tools/ci_setup.ml
Allowing failure on windows as we hit https://github.com/libuv/libuv/issues/3622 quite a lot.
> More win tests

- awesome-js_of_ocaml.md
- manual/debug.wiki
- manual/environment-variable.wiki
- manual/menu.wiki
And start to collect links on external resources in awesome-js_of_ocaml.md
Fix #1044 
Fix #1217
> Doc: js stacktrace and env variable resolution

- CHANGES.md
- compiler/lib/parse_bytecode.ml
- compiler/ppx/ppx_optcomp_light.ml
- compiler/ppx/properties.ml
> Compiler: add support for OCaml 4.14.3+trunk

- CHANGES.md
- runtime/js/fs.js
fix https://github.com/ocsigen/js_of_ocaml/issues/1847
> runtime: fix path normalisation

- benchmarks/common.ml
- benchmarks/run.ml
- compiler/bin-wasm_of_ocaml/compile.ml
> Bench: add wasm support to benchmarks

- CHANGES.md
- compiler/tests-io/dune
- compiler/tests-io/gh1856.ml
- runtime/js/fs_fake.js
> Fs_fake: fix offset computation

- benchmarks/Makefile
- benchmarks/common.ml
- benchmarks/dune
- benchmarks/report.ml
- benchmarks/run.ml
On top of #1857
Supersedes #1842
> Refactor benchmark script and support current-bench

- CHANGES.md
- lib/js_of_ocaml/json.ml
- lib/tests/dune.inc
- lib/tests/gen-rules/gen.ml
- lib/tests/test_json.ml
Make it work with native ints and JavaScript values
> Json.output improvements

- compiler/lib/stdlib.ml
Using `tail_mod_cons` makes the traces of js_of_ocaml.link readable and easier to understand. In addition, it avoids the `slow_map` path so this is also faster. This patch implements `List.map` using `tail_mod_cons` starting from when it is supported (4.14.0).
> Use `tail_mod_cons` for List.map

- CHANGES.md
- toplevel/bin/jsoo_mkcmis.ml
- toplevel/test/dune
- toplevel/test/test_toplevel.expected
- toplevel/test/test_toplevel1.ml
- toplevel/test/test_toplevel2.ml
The target and the effect mode was not initialized.
> Fix jsoo_mkcmis

- Makefile
- bench.Dockerfile
- benchmarks/Makefile
- benchmarks/report-jsoo-cb.config
- benchmarks/report-wasm-cb.config
- benchmarks/run.ml
- benchmarks/sources/ml/splay.ml
> Add benchmarking suite targeting current-bench

- lib/js_of_ocaml/sys_js.mli
> Sys_js: fix doc of read_file when file does not exist

- compiler/lib/driver.ml
- compiler/lib/inline.ml
> Some small improvement to the optimization passes

- compiler/lib/global_deadcode.ml
An IsInt test should retain just the block, not its contents.
> Global dead code: small improvement
